#!/bin/bash
# Round 0B database foundation — schemas, roles, pgvector, schema_version only.
# Safe to source (non-executable bind-mount on Windows) or execute.
(
set -euo pipefail

: "${POSTGRES_DB:?POSTGRES_DB required}"
: "${POSTGRES_USER:?POSTGRES_USER required}"
: "${N8N_DB_USER:?N8N_DB_USER required}"
: "${N8N_DB_PASSWORD:?N8N_DB_PASSWORD required}"
: "${RESEARCH_DB_USER:?RESEARCH_DB_USER required}"
: "${RESEARCH_DB_PASSWORD:?RESEARCH_DB_PASSWORD required}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<EOSQL
CREATE EXTENSION IF NOT EXISTS vector;

CREATE SCHEMA IF NOT EXISTS n8n AUTHORIZATION ${POSTGRES_USER};
CREATE SCHEMA IF NOT EXISTS research AUTHORIZATION ${POSTGRES_USER};

DO \$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${N8N_DB_USER}') THEN
    CREATE ROLE ${N8N_DB_USER} LOGIN PASSWORD '${N8N_DB_PASSWORD}';
  END IF;
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${RESEARCH_DB_USER}') THEN
    CREATE ROLE ${RESEARCH_DB_USER} LOGIN PASSWORD '${RESEARCH_DB_PASSWORD}';
  END IF;
END
\$\$;

GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${N8N_DB_USER};
GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${RESEARCH_DB_USER};
GRANT CREATE ON DATABASE ${POSTGRES_DB} TO ${N8N_DB_USER};
GRANT CREATE ON DATABASE ${POSTGRES_DB} TO ${RESEARCH_DB_USER};

GRANT USAGE, CREATE ON SCHEMA n8n TO ${N8N_DB_USER};
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA n8n TO ${N8N_DB_USER};
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA n8n TO ${N8N_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA n8n
  GRANT ALL PRIVILEGES ON TABLES TO ${N8N_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA n8n
  GRANT ALL PRIVILEGES ON SEQUENCES TO ${N8N_DB_USER};
ALTER ROLE ${N8N_DB_USER} SET search_path TO n8n;

GRANT USAGE, CREATE ON SCHEMA research TO ${RESEARCH_DB_USER};
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA research TO ${RESEARCH_DB_USER};
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA research TO ${RESEARCH_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA research
  GRANT ALL PRIVILEGES ON TABLES TO ${RESEARCH_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA research
  GRANT ALL PRIVILEGES ON SEQUENCES TO ${RESEARCH_DB_USER};
ALTER ROLE ${RESEARCH_DB_USER} SET search_path TO research;

REVOKE ALL ON SCHEMA research FROM ${N8N_DB_USER};
REVOKE ALL ON SCHEMA n8n FROM ${RESEARCH_DB_USER};

CREATE TABLE IF NOT EXISTS research.schema_version (
  version INTEGER PRIMARY KEY,
  applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  note TEXT NOT NULL
);

INSERT INTO research.schema_version (version, note)
VALUES (1, 'Round 0B foundation: schemas, roles, pgvector')
ON CONFLICT (version) DO NOTHING;

GRANT SELECT, INSERT, UPDATE, DELETE ON research.schema_version TO ${RESEARCH_DB_USER};
EOSQL

echo "Round 0B database initialization completed."
)
