-- =====================================================================
-- SENTINEL RESEARCH LAB — PHASE 1 — SCHEMA-8 CATALOG EVIDENCE BUNDLE
-- =====================================================================
-- Purpose : read-only extraction of authoritative schema-8 catalog state
-- Closes  : Codex findings #1 (function ACLs), #2 (role/table matrix),
--           #3 (preflight expected inventories)
-- Mode    : READ ONLY. Executes no DDL, no DML, no locks, no temp objects.
-- Safety  : uses ONLY pg_catalog and built-in functions. Never calls any
--           research.* function, so evidence is not generated by the code
--           under review.
--
-- EXECUTION
--   Run the WHOLE FILE in ONE session, ONE transaction, ending in ROLLBACK.
--   Sections are separated by banner comments and may be read individually,
--   but must not be executed in separate transactions: the start/end drift
--   digests (G00/G99) are only meaningful across a single snapshot.
--
--   psql --no-psqlrc --set ON_ERROR_STOP=1 -f SRL_Phase1_catalog_snapshot.sql
--
--   Capture stdout/stderr as raw bytes, decode UTF-8 explicitly.
--
-- HARD FLOOR
--   PostgreSQL 11+. G01 returns BLOCKED if lower. Below 11 there is no
--   built-in sha256() and pg_proc.prokind does not exist; the bundle is
--   not valid and must not be adapted by hand.
--
-- TARGET SCHEMA
--   'research' throughout. It appears as a literal in every WHERE clause
--   deliberately — no variable, no substitution, no room to widen scope.
-- =====================================================================


-- =====================================================================
-- READ-ONLY PREAMBLE  (mandatory, do not remove)
-- =====================================================================
SET default_transaction_read_only = on;

BEGIN;
SET TRANSACTION READ ONLY, ISOLATION LEVEL REPEATABLE READ;
SET LOCAL statement_timeout                     = '120s';
SET LOCAL lock_timeout                          = '5s';
SET LOCAL idle_in_transaction_session_timeout   = '300s';
SET LOCAL search_path                           = pg_catalog;

-- Note on isolation: REPEATABLE READ stabilises user-issued SELECTs against
-- catalog tables. It does NOT stabilise has_*_privilege(), which performs
-- internal syscache lookups and may observe fresher state. The G00/G99 drift
-- digest pair is the actual guarantee that nothing changed mid-capture.


-- =====================================================================
-- G00 — DRIFT DIGEST (START)                       EV-DRIFT-001
-- =====================================================================
-- Proves: the catalog did not change during capture (compare to G99).
-- Row key: none, single value.
SELECT
  'EV-DRIFT-001'                                    AS evidence_set,
  'start'                                           AS position,
  encode(sha256(convert_to(
    coalesce(string_agg(x, chr(30) ORDER BY x COLLATE "C"), ''), 'UTF8')), 'hex') AS drift_digest
FROM (
  SELECT 'c' || chr(31) || c.relname || chr(31) || coalesce(c.relacl::text, '\N') AS x
  FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'research'
  UNION ALL
  SELECT 'p' || chr(31) || p.proname || chr(31)
         || pg_get_function_identity_arguments(p.oid) || chr(31)
         || coalesce(p.proacl::text, '\N')
  FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
  WHERE n.nspname = 'research'
  UNION ALL
  SELECT 'n' || chr(31) || n.nspname || chr(31) || coalesce(n.nspacl::text, '\N')
  FROM pg_namespace n WHERE n.nspname = 'research'
) t;


-- =====================================================================
-- G01 — DATABASE BASELINE AND VERSION GUARD        EV-BASELINE-001
-- =====================================================================
-- Proves: which server and database this evidence describes; that the
--         version floor for sha256()/prokind is met.
-- STOP IF version_guard = 'BLOCKED'.
SELECT
  'EV-BASELINE-001'                                 AS evidence_set,
  current_database()                                AS database_name,
  current_setting('server_version')                 AS server_version,
  current_setting('server_version_num')::int        AS server_version_num,
  CASE WHEN current_setting('server_version_num')::int >= 110000
       THEN 'OK' ELSE 'BLOCKED' END                 AS version_guard,
  current_setting('lc_collate')                     AS lc_collate,
  current_setting('lc_ctype')                       AS lc_ctype,
  current_user                                      AS captured_by,
  (SELECT rolsuper FROM pg_roles WHERE rolname = current_user) AS captured_by_is_superuser,
  current_setting('transaction_read_only')          AS txn_read_only;

-- Self-test of the digest primitive. MUST return exactly
--   e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
-- Any other value means the digest implementation is defective and the
-- whole evidence pack is void.
SELECT
  'EV-BASELINE-001'                                 AS evidence_set,
  'empty_digest_selftest'                           AS check_name,
  encode(sha256(''::bytea), 'hex')                  AS actual,
  'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855' AS expected,
  (encode(sha256(''::bytea), 'hex')
   = 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855') AS pass;


-- =====================================================================
-- G02 — ROLES AND ATTRIBUTES                       EV-ROLE-001
-- =====================================================================
-- Proves: the complete role population, including built-in pg_* roles.
-- pg_* roles are NOT excluded: pg_read_all_data / pg_write_all_data
-- (PG14+) confer effective access and are load-bearing for this boundary.
-- Row key: rolname
SELECT
  'EV-ROLE-001'                                     AS evidence_set,
  r.rolname                                         AS row_key,
  r.rolname,
  r.rolcanlogin,
  r.rolinherit,
  r.rolsuper,
  r.rolcreaterole,
  r.rolcreatedb,
  r.rolreplication,
  r.rolbypassrls,
  (r.rolname LIKE 'pg\_%')                          AS is_builtin_role
FROM pg_roles r
ORDER BY r.rolname COLLATE "C";


-- =====================================================================
-- G03 — ROLE MEMBERSHIP GRAPH (TRANSITIVE)         EV-ROLE-002
-- =====================================================================
-- Proves: every path by which a role acquires another role's privileges,
--         and whether that path is automatic (INHERIT) or requires SET ROLE.
-- inherited_auto  : privileges apply without action  -> pg_has_role(...,'USAGE')
-- set_role_only   : privileges reachable via SET ROLE -> 'MEMBER' but not 'USAGE'
-- A NOINHERIT role showing set_role_only = true is still a live write path
-- and must appear in the boundary analysis.
-- Row key: member_role|granted_role|depth
WITH RECURSIVE mem AS (
  SELECT am.member AS member_oid, am.roleid AS role_oid, 1 AS depth,
         ARRAY[am.roleid] AS path
  FROM pg_auth_members am
  UNION ALL
  SELECT m.member_oid, am.roleid, m.depth + 1, m.path || am.roleid
  FROM mem m
  JOIN pg_auth_members am ON am.member = m.role_oid
  WHERE NOT am.roleid = ANY(m.path)          -- cycle guard
    AND m.depth < 32                         -- runaway guard
)
SELECT
  'EV-ROLE-002'                                     AS evidence_set,
  mr.rolname || '|' || gr.rolname || '|' || mem.depth::text AS row_key,
  mr.rolname                                        AS member_role,
  gr.rolname                                        AS granted_role,
  mem.depth,
  mr.rolinherit                                     AS member_inherits,
  pg_has_role(mr.oid, gr.oid, 'USAGE')              AS inherited_auto,
  pg_has_role(mr.oid, gr.oid, 'MEMBER')             AS reachable_member,
  (pg_has_role(mr.oid, gr.oid, 'MEMBER')
   AND NOT pg_has_role(mr.oid, gr.oid, 'USAGE'))    AS set_role_only
FROM mem
JOIN pg_roles mr ON mr.oid = mem.member_oid
JOIN pg_roles gr ON gr.oid = mem.role_oid
ORDER BY mr.rolname COLLATE "C", gr.rolname COLLATE "C", mem.depth;


-- =====================================================================
-- G04 — SCHEMAS, OWNERS, SCHEMA ACLS               EV-SCHEMA-001
-- =====================================================================
-- NULL nspacl expansion: acldefault('n', owner) = owner holds USAGE+CREATE,
-- PUBLIC holds NOTHING. (The historical PUBLIC grant on schema `public` is
-- an explicit initdb grant, not a default, and PG15 removed CREATE from it.)
-- LEFT JOIN LATERAL ... ON TRUE so a fully-revoked schema still emits a row.
-- Row key: schema|grantee|privilege
SELECT
  'EV-SCHEMA-001'                                   AS evidence_set,
  n.nspname || '|' || coalesce(CASE WHEN a.grantee = 0 THEN 'PUBLIC'
                                    ELSE pg_get_userbyid(a.grantee) END, '\N')
            || '|' || coalesce(a.privilege_type, '\N')  AS row_key,
  n.nspname                                         AS schema_name,
  pg_get_userbyid(n.nspowner)                       AS owner,
  (n.nspacl IS NULL)                                AS acl_is_default,
  coalesce(n.nspacl::text, '\N')                    AS raw_nspacl,
  CASE WHEN a.grantee = 0 THEN 'PUBLIC' ELSE pg_get_userbyid(a.grantee) END AS grantee,
  CASE WHEN a.grantor = 0 THEN 'PUBLIC' ELSE pg_get_userbyid(a.grantor) END AS grantor,
  a.privilege_type,
  a.is_grantable
FROM pg_namespace n
LEFT JOIN LATERAL aclexplode(coalesce(n.nspacl, acldefault('n', n.nspowner))) a ON TRUE
WHERE n.nspname NOT LIKE 'pg\_%'
ORDER BY n.nspname COLLATE "C",
         coalesce(CASE WHEN a.grantee = 0 THEN 'PUBLIC'
                       ELSE pg_get_userbyid(a.grantee) END, '') COLLATE "C",
         coalesce(a.privilege_type, '') COLLATE "C";

-- Effective schema USAGE per role. This is the gate that has_table_privilege()
-- and has_function_privilege() do NOT check. Without USAGE on `research`,
-- a table or function privilege is unexercisable.
-- Row key: schema|role
SELECT
  'EV-SCHEMA-002'                                   AS evidence_set,
  n.nspname || '|' || r.rolname                     AS row_key,
  n.nspname                                         AS schema_name,
  r.rolname,
  r.rolsuper                                        AS superuser_derived,
  has_schema_privilege(r.oid, n.oid, 'USAGE')       AS effective_usage,
  has_schema_privilege(r.oid, n.oid, 'CREATE')      AS effective_create
FROM pg_namespace n
CROSS JOIN pg_roles r
WHERE n.nspname NOT LIKE 'pg\_%'
ORDER BY n.nspname COLLATE "C", r.rolname COLLATE "C";


-- =====================================================================
-- G05 — EXTENSIONS                                 EV-EXT-001
-- =====================================================================
-- Proves: the literal extension inventory that replaces Revision 7's
--         "vector (and any pinned baseline only)".
-- Row key: extension_name
SELECT
  'EV-EXT-001'                                      AS evidence_set,
  e.extname                                         AS row_key,
  e.extname,
  e.extversion,
  n.nspname                                         AS extension_schema,
  pg_get_userbyid(e.extowner)                       AS owner,
  e.extrelocatable
FROM pg_extension e
JOIN pg_namespace n ON n.oid = e.extnamespace
ORDER BY e.extname COLLATE "C";


-- =====================================================================
-- G06 — FUNCTION INVENTORY                         EV-FUNCTION-001
-- =====================================================================
-- Proves: the exact schema-8 function population, settling the disputed
--         "54 functions" claim. Population membership is explicit on three
--         axes so the count is reproducible:
--           prokind             f=function p=procedure a=aggregate w=window
--           is_extension_member true => owned by an extension (e.g. vector);
--                               MUST NOT be frozen or revoked
--           returns_trigger     trigger functions, distinct freeze semantics
-- Every overload is a separate row; identity is
--   (schema, name, pg_get_function_identity_arguments) which is unique in PG.
-- OID is reported for cross-referencing within this snapshot ONLY. It is
-- excluded from row_key and from every digest: OIDs are not stable across
-- dump/restore.
-- Row key: schema.name(identity_args)
SELECT
  'EV-FUNCTION-001'                                 AS evidence_set,
  n.nspname || '.' || p.proname || '('
    || pg_get_function_identity_arguments(p.oid) || ')' AS row_key,
  p.oid                                             AS function_oid_unstable,
  n.nspname                                         AS schema_name,
  p.proname                                         AS function_name,
  pg_get_function_identity_arguments(p.oid)         AS identity_args,
  pg_get_function_result(p.oid)                     AS result_type,
  pg_get_userbyid(p.proowner)                       AS owner,
  l.lanname                                         AS language,
  p.prokind,
  CASE WHEN p.prosecdef THEN 'DEFINER' ELSE 'INVOKER' END AS security_mode,
  p.provolatile,
  p.proleakproof,
  (p.prorettype = 'pg_catalog.trigger'::regtype)    AS returns_trigger,
  EXISTS (SELECT 1 FROM pg_depend d
          WHERE d.classid = 'pg_proc'::regclass
            AND d.objid = p.oid AND d.deptype = 'e') AS is_extension_member,
  (p.proacl IS NULL)                                AS acl_is_default,
  coalesce(p.proacl::text, '\N')                    AS raw_proacl
FROM pg_proc p
JOIN pg_namespace n ON n.oid = p.pronamespace
JOIN pg_language  l ON l.oid = p.prolang
WHERE n.nspname = 'research'
ORDER BY n.nspname COLLATE "C",
         p.proname COLLATE "C",
         pg_get_function_identity_arguments(p.oid) COLLATE "C";

-- Population counts, so the disputed number is stated as a derived fact.
SELECT
  'EV-FUNCTION-002'                                 AS evidence_set,
  p.prokind,
  EXISTS (SELECT 1 FROM pg_depend d
          WHERE d.classid = 'pg_proc'::regclass
            AND d.objid = p.oid AND d.deptype = 'e') AS is_extension_member,
  (p.prorettype = 'pg_catalog.trigger'::regtype)    AS returns_trigger,
  count(*)                                          AS function_count
FROM pg_proc p
JOIN pg_namespace n ON n.oid = p.pronamespace
WHERE n.nspname = 'research'
GROUP BY 2, 3, 4, p.prokind
ORDER BY p.prokind COLLATE "C", 3, 4;


-- =====================================================================
-- G07 — FUNCTION ACLS, DIRECT AND DEFAULT          EV-FUNCTION-ACL-001
-- =====================================================================
-- *** THIS QUERY IS THE ONE THAT SETTLES CODEX FINDING #1. ***
--
-- proacl IS NULL does NOT mean "no grants". It means the built-in default
-- applies, and for functions that default is:
--       =X/owner        -> PUBLIC HOLDS EXECUTE
--       owner=X/owner   -> owner holds EXECUTE
-- Revision 7 asserts PUBLIC EXECUTE = N for all 54 functions. If any function
-- has proacl IS NULL, that assertion is false for that function.
--
-- grantee = 0 in aclexplode() output is PUBLIC. It renders as '-' under
-- ::regrole and errors or misleads under pg_get_userbyid(0), so it is
-- CASE-handled explicitly.
--
-- LEFT JOIN ... ON TRUE is required: a function whose proacl is an explicitly
-- empty array '{}' (everything revoked) yields zero aclexplode rows and would
-- silently vanish from the inventory under an inner join.
-- Row key: schema.name(identity_args)|grantee|privilege
SELECT
  'EV-FUNCTION-ACL-001'                             AS evidence_set,
  n.nspname || '.' || p.proname || '('
    || pg_get_function_identity_arguments(p.oid) || ')'
    || '|' || coalesce(CASE WHEN a.grantee = 0 THEN 'PUBLIC'
                            ELSE pg_get_userbyid(a.grantee) END, '\N')
    || '|' || coalesce(a.privilege_type, '\N')      AS row_key,
  n.nspname                                         AS schema_name,
  p.proname                                         AS function_name,
  pg_get_function_identity_arguments(p.oid)         AS identity_args,
  pg_get_userbyid(p.proowner)                       AS owner,
  (p.proacl IS NULL)                                AS acl_is_default,
  CASE WHEN p.proacl IS NULL
       THEN 'DEFAULT_EXPANDED_acldefault(f,owner)'
       ELSE 'EXPLICIT_proacl' END                   AS acl_source,
  CASE WHEN a.grantee = 0 THEN 'PUBLIC' ELSE pg_get_userbyid(a.grantee) END AS grantee,
  (a.grantee = 0)                                   AS grantee_is_public,
  (a.grantee = p.proowner)                          AS grantee_is_owner,
  CASE WHEN a.grantor = 0 THEN 'PUBLIC' ELSE pg_get_userbyid(a.grantor) END AS grantor,
  a.privilege_type,
  a.is_grantable
FROM pg_proc p
JOIN pg_namespace n ON n.oid = p.pronamespace
LEFT JOIN LATERAL aclexplode(coalesce(p.proacl, acldefault('f', p.proowner))) a ON TRUE
WHERE n.nspname = 'research'
ORDER BY n.nspname COLLATE "C",
         p.proname COLLATE "C",
         pg_get_function_identity_arguments(p.oid) COLLATE "C",
         coalesce(CASE WHEN a.grantee = 0 THEN 'PUBLIC'
                       ELSE pg_get_userbyid(a.grantee) END, '') COLLATE "C",
         coalesce(a.privilege_type, '') COLLATE "C";

-- Direct contradiction test against Revision 7 §13.3.
-- Any row returned here falsifies "PUBLIC EXECUTE = N for all functions".
SELECT
  'EV-FUNCTION-ACL-002'                             AS evidence_set,
  n.nspname || '.' || p.proname || '('
    || pg_get_function_identity_arguments(p.oid) || ')' AS row_key,
  (p.proacl IS NULL)                                AS acl_is_default,
  'PUBLIC holds EXECUTE — contradicts Rev7 §13.3 PUBLIC EXECUTE = N' AS finding
FROM pg_proc p
JOIN pg_namespace n ON n.oid = p.pronamespace
CROSS JOIN LATERAL aclexplode(coalesce(p.proacl, acldefault('f', p.proowner))) a
WHERE n.nspname = 'research'
  AND a.grantee = 0
  AND a.privilege_type = 'EXECUTE'
ORDER BY 2 COLLATE "C";


-- =====================================================================
-- G08 — EFFECTIVE FUNCTION EXECUTE, ALL ROLES      EV-FUNCTION-EXEC-001
-- =====================================================================
-- Cross product of every function with EVERY role in the cluster — not the
-- five roles Revision 7 assumes. Five boolean columns decompose the single
-- word "effective" into its distinct meanings:
--
--   granted_direct        an ACL row names this role explicitly
--   granted_via_public    an ACL row names PUBLIC
--   granted_via_inherit   an ACL row names a role this role inherits (auto)
--   set_role_only         reachable only after SET ROLE (NOINHERIT member)
--   superuser_derived     role is superuser; has_*_privilege is true always
--
--   effective_execute     has_function_privilege() — the server's own answer
--   exercisable           effective_execute AND schema USAGE
--
-- has_function_privilege() does NOT check schema USAGE. A role with EXECUTE
-- but no USAGE on `research` cannot call the function. Freeze scope must be
-- driven by `exercisable`, not by `effective_execute`.
-- Row key: schema.name(identity_args)|role
SELECT
  'EV-FUNCTION-EXEC-001'                            AS evidence_set,
  fn.row_key || '|' || r.rolname                    AS row_key,
  fn.schema_name,
  fn.function_name,
  fn.identity_args,
  r.rolname,
  r.rolcanlogin,
  r.rolinherit,
  r.rolsuper                                        AS superuser_derived,
  has_function_privilege(r.oid, fn.oid, 'EXECUTE')  AS effective_execute,
  has_schema_privilege(r.oid, 'research', 'USAGE')  AS schema_usage,
  (has_function_privilege(r.oid, fn.oid, 'EXECUTE')
   AND has_schema_privilege(r.oid, 'research', 'USAGE')) AS exercisable,
  EXISTS (SELECT 1 FROM aclexplode(fn.eff_acl) a
          WHERE a.grantee = r.oid AND a.privilege_type = 'EXECUTE')  AS granted_direct,
  EXISTS (SELECT 1 FROM aclexplode(fn.eff_acl) a
          WHERE a.grantee = 0     AND a.privilege_type = 'EXECUTE')  AS granted_via_public,
  EXISTS (SELECT 1 FROM aclexplode(fn.eff_acl) a
          WHERE a.privilege_type = 'EXECUTE' AND a.grantee <> 0
            AND a.grantee <> r.oid
            AND pg_has_role(r.oid, a.grantee, 'USAGE'))              AS granted_via_inherit,
  EXISTS (SELECT 1 FROM aclexplode(fn.eff_acl) a
          WHERE a.privilege_type = 'EXECUTE' AND a.grantee <> 0
            AND a.grantee <> r.oid
            AND pg_has_role(r.oid, a.grantee, 'MEMBER')
            AND NOT pg_has_role(r.oid, a.grantee, 'USAGE'))          AS set_role_only
FROM (
  SELECT p.oid,
         n.nspname AS schema_name,
         p.proname AS function_name,
         pg_get_function_identity_arguments(p.oid) AS identity_args,
         n.nspname || '.' || p.proname || '('
           || pg_get_function_identity_arguments(p.oid) || ')' AS row_key,
         coalesce(p.proacl, acldefault('f', p.proowner)) AS eff_acl
  FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
  WHERE n.nspname = 'research'
) fn
CROSS JOIN pg_roles r
ORDER BY fn.row_key COLLATE "C", r.rolname COLLATE "C";


-- =====================================================================
-- G09 — BASE TABLES AND OWNERS                     EV-TABLE-001
-- =====================================================================
-- relkind 'r' ordinary table, 'p' partitioned table. Both are base tables.
-- Row key: schema.table
SELECT
  'EV-TABLE-001'                                    AS evidence_set,
  n.nspname || '.' || c.relname                     AS row_key,
  c.oid                                             AS relation_oid_unstable,
  n.nspname                                         AS schema_name,
  c.relname                                         AS table_name,
  c.relkind,
  pg_get_userbyid(c.relowner)                       AS owner,
  c.relrowsecurity,
  c.relforcerowsecurity,
  (c.relacl IS NULL)                                AS acl_is_default,
  coalesce(c.relacl::text, '\N')                    AS raw_relacl
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE n.nspname = 'research' AND c.relkind IN ('r', 'p')
ORDER BY n.nspname COLLATE "C", c.relname COLLATE "C";


-- =====================================================================
-- G10 — RELATION ACLS, DIRECT AND DEFAULT          EV-TABLE-ACL-001
-- =====================================================================
-- relacl IS NULL expands via acldefault('r', owner): owner holds ALL,
-- PUBLIC holds NOTHING. This is the OPPOSITE of the function default and
-- must not be conflated with it.
-- Row key: schema.table|grantee|privilege
SELECT
  'EV-TABLE-ACL-001'                                AS evidence_set,
  n.nspname || '.' || c.relname
    || '|' || coalesce(CASE WHEN a.grantee = 0 THEN 'PUBLIC'
                            ELSE pg_get_userbyid(a.grantee) END, '\N')
    || '|' || coalesce(a.privilege_type, '\N')      AS row_key,
  n.nspname                                         AS schema_name,
  c.relname                                         AS table_name,
  pg_get_userbyid(c.relowner)                       AS owner,
  (c.relacl IS NULL)                                AS acl_is_default,
  CASE WHEN c.relacl IS NULL
       THEN 'DEFAULT_EXPANDED_acldefault(r,owner)'
       ELSE 'EXPLICIT_relacl' END                   AS acl_source,
  CASE WHEN a.grantee = 0 THEN 'PUBLIC' ELSE pg_get_userbyid(a.grantee) END AS grantee,
  (a.grantee = 0)                                   AS grantee_is_public,
  (a.grantee = c.relowner)                          AS grantee_is_owner,
  a.privilege_type,
  a.is_grantable
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace
LEFT JOIN LATERAL aclexplode(coalesce(c.relacl, acldefault('r', c.relowner))) a ON TRUE
WHERE n.nspname = 'research' AND c.relkind IN ('r', 'p')
ORDER BY n.nspname COLLATE "C", c.relname COLLATE "C",
         coalesce(CASE WHEN a.grantee = 0 THEN 'PUBLIC'
                       ELSE pg_get_userbyid(a.grantee) END, '') COLLATE "C",
         coalesce(a.privilege_type, '') COLLATE "C";


-- =====================================================================
-- G11 — EFFECTIVE TABLE WRITE MATRIX               EV-TABLE-WRITE-001
-- =====================================================================
-- *** THIS QUERY IS THE ONE THAT SETTLES CODEX FINDING #2. ***
--
-- Every base table crossed with EVERY role and every privilege — replacing
-- Revision 7's five-role matrix and its uniform "DELETE = Y" claim.
-- Same five-way decomposition of "effective" as G08.
-- Row key: schema.table|role|privilege
SELECT
  'EV-TABLE-WRITE-001'                              AS evidence_set,
  t.row_key || '|' || r.rolname || '|' || pr.priv   AS row_key,
  t.schema_name,
  t.table_name,
  t.owner,
  r.rolname,
  r.rolcanlogin,
  r.rolinherit,
  r.rolsuper                                        AS superuser_derived,
  pr.priv                                           AS privilege,
  has_table_privilege(r.oid, t.oid, pr.priv)        AS effective_privilege,
  has_schema_privilege(r.oid, 'research', 'USAGE')  AS schema_usage,
  (has_table_privilege(r.oid, t.oid, pr.priv)
   AND has_schema_privilege(r.oid, 'research', 'USAGE')) AS exercisable,
  (r.oid = t.relowner)                              AS role_is_owner,
  EXISTS (SELECT 1 FROM aclexplode(t.eff_acl) a
          WHERE a.grantee = r.oid AND a.privilege_type = pr.priv)   AS granted_direct,
  EXISTS (SELECT 1 FROM aclexplode(t.eff_acl) a
          WHERE a.grantee = 0     AND a.privilege_type = pr.priv)   AS granted_via_public,
  EXISTS (SELECT 1 FROM aclexplode(t.eff_acl) a
          WHERE a.privilege_type = pr.priv AND a.grantee <> 0
            AND a.grantee <> r.oid
            AND pg_has_role(r.oid, a.grantee, 'USAGE'))             AS granted_via_inherit,
  EXISTS (SELECT 1 FROM aclexplode(t.eff_acl) a
          WHERE a.privilege_type = pr.priv AND a.grantee <> 0
            AND a.grantee <> r.oid
            AND pg_has_role(r.oid, a.grantee, 'MEMBER')
            AND NOT pg_has_role(r.oid, a.grantee, 'USAGE'))         AS set_role_only
FROM (
  SELECT c.oid, c.relowner,
         n.nspname AS schema_name, c.relname AS table_name,
         pg_get_userbyid(c.relowner) AS owner,
         n.nspname || '.' || c.relname AS row_key,
         coalesce(c.relacl, acldefault('r', c.relowner)) AS eff_acl
  FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'research' AND c.relkind IN ('r', 'p')
) t
CROSS JOIN pg_roles r
CROSS JOIN LATERAL (VALUES ('SELECT'),('INSERT'),('UPDATE'),('DELETE'),
                           ('TRUNCATE'),('REFERENCES'),('TRIGGER')) AS pr(priv)
ORDER BY t.row_key COLLATE "C", r.rolname COLLATE "C", pr.priv COLLATE "C";

-- Contradiction test against Revision 7 §13.4 "research_app DELETE = Y".
-- Emits one row per table stating the actual answer, so both confirmation
-- and contradiction are provable from the same query.
SELECT
  'EV-TABLE-WRITE-002'                              AS evidence_set,
  n.nspname || '.' || c.relname                     AS row_key,
  has_table_privilege('research_app', c.oid, 'DELETE') AS research_app_delete_actual,
  CASE WHEN has_table_privilege('research_app', c.oid, 'DELETE')
       THEN 'CONFIRMS Rev7 §13.4 DELETE=Y'
       ELSE 'CONTRADICTS Rev7 §13.4 DELETE=Y' END   AS verdict
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE n.nspname = 'research' AND c.relkind IN ('r', 'p')
  AND EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'research_app')
ORDER BY 2 COLLATE "C";


-- =====================================================================
-- G12 — COLUMN ACLS                                EV-COLUMN-ACL-001
-- =====================================================================
-- IMPORTANT AND EASY TO GET BACKWARDS:
--   attacl IS NULL does NOT expand to a PUBLIC grant. acldefault('c', owner)
--   is the EMPTY acl. NULL attacl means "no column-specific grants exist;
--   access is governed entirely by the table-level ACL."
--   This is the opposite situation from proacl (G07) and conflating the two
--   produces errors in both directions.
--
-- Every non-dropped column is emitted, including those with no ACL, so the
-- ABSENCE of a column grant is provable rather than merely unstated.
-- Row key: schema.table.column|grantee|privilege
SELECT
  'EV-COLUMN-ACL-001'                               AS evidence_set,
  n.nspname || '.' || c.relname || '.' || att.attname
    || '|' || coalesce(CASE WHEN a.grantee = 0 THEN 'PUBLIC'
                            ELSE pg_get_userbyid(a.grantee) END, '\N')
    || '|' || coalesce(a.privilege_type, '\N')      AS row_key,
  n.nspname                                         AS schema_name,
  c.relname                                         AS table_name,
  att.attnum                                        AS ordinal_position,
  att.attname                                       AS column_name,
  (att.attacl IS NULL)                              AS no_column_specific_acl,
  coalesce(att.attacl::text, '\N')                  AS raw_attacl,
  CASE WHEN a.grantee = 0 THEN 'PUBLIC' ELSE pg_get_userbyid(a.grantee) END AS grantee,
  a.privilege_type,
  a.is_grantable
FROM pg_class c
JOIN pg_namespace n  ON n.oid = c.relnamespace
JOIN pg_attribute att ON att.attrelid = c.oid
LEFT JOIN LATERAL aclexplode(att.attacl) a ON TRUE   -- no acldefault: columns have none
WHERE n.nspname = 'research' AND c.relkind IN ('r', 'p')
  AND att.attnum > 0 AND NOT att.attisdropped
ORDER BY n.nspname COLLATE "C", c.relname COLLATE "C", att.attnum,
         coalesce(CASE WHEN a.grantee = 0 THEN 'PUBLIC'
                       ELSE pg_get_userbyid(a.grantee) END, '') COLLATE "C",
         coalesce(a.privilege_type, '') COLLATE "C";

-- Effective column privileges. has_column_privilege() correctly accounts for
-- table-level grants (a table UPDATE grant confers UPDATE on all columns), so
-- this is the authoritative answer to Revision 7's "UPDATE on all columns".
-- Restricted to roles that can log in or are reachable, to bound row count.
-- Row key: schema.table.column|role|privilege
SELECT
  'EV-COLUMN-EFF-001'                               AS evidence_set,
  n.nspname || '.' || c.relname || '.' || att.attname
    || '|' || r.rolname || '|' || pr.priv           AS row_key,
  n.nspname                                         AS schema_name,
  c.relname                                         AS table_name,
  att.attname                                       AS column_name,
  att.attnum                                        AS ordinal_position,
  r.rolname,
  r.rolsuper                                        AS superuser_derived,
  pr.priv                                           AS privilege,
  has_column_privilege(r.oid, c.oid, att.attnum, pr.priv) AS effective_privilege,
  (att.attacl IS NOT NULL)                          AS has_column_specific_acl
FROM pg_class c
JOIN pg_namespace n   ON n.oid = c.relnamespace
JOIN pg_attribute att ON att.attrelid = c.oid
CROSS JOIN pg_roles r
CROSS JOIN LATERAL (VALUES ('SELECT'),('INSERT'),('UPDATE'),('REFERENCES')) AS pr(priv)
WHERE n.nspname = 'research' AND c.relkind IN ('r', 'p')
  AND att.attnum > 0 AND NOT att.attisdropped
  AND (r.rolcanlogin OR r.rolname IN ('research_app','n8n_app',
                                      'research_governance','research_test'))
ORDER BY n.nspname COLLATE "C", c.relname COLLATE "C", att.attnum,
         r.rolname COLLATE "C", pr.priv COLLATE "C";


-- =====================================================================
-- G13 — VIEWS AND MATERIALIZED VIEWS               EV-VIEW-001
-- =====================================================================
-- Replaces Revision 7's "Appendix A.2 baseline set" with a literal list.
-- Row key: schema.name
SELECT
  'EV-VIEW-001'                                     AS evidence_set,
  n.nspname || '.' || c.relname                     AS row_key,
  n.nspname                                         AS schema_name,
  c.relname                                         AS view_name,
  c.relkind,                                        -- v = view, m = matview
  pg_get_userbyid(c.relowner)                       AS owner,
  (c.relacl IS NULL)                                AS acl_is_default,
  coalesce(c.relacl::text, '\N')                    AS raw_relacl,
  md5(pg_get_viewdef(c.oid, true))                  AS viewdef_md5
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE n.nspname = 'research' AND c.relkind IN ('v', 'm')
ORDER BY n.nspname COLLATE "C", c.relname COLLATE "C";


-- =====================================================================
-- G14 — SEQUENCES AND SEQUENCE ACLS                EV-SEQUENCE-001
-- =====================================================================
-- acldefault('s', owner): owner ALL, PUBLIC nothing.
-- Row key: schema.name|grantee|privilege
SELECT
  'EV-SEQUENCE-001'                                 AS evidence_set,
  n.nspname || '.' || c.relname
    || '|' || coalesce(CASE WHEN a.grantee = 0 THEN 'PUBLIC'
                            ELSE pg_get_userbyid(a.grantee) END, '\N')
    || '|' || coalesce(a.privilege_type, '\N')      AS row_key,
  n.nspname                                         AS schema_name,
  c.relname                                         AS sequence_name,
  pg_get_userbyid(c.relowner)                       AS owner,
  (c.relacl IS NULL)                                AS acl_is_default,
  CASE WHEN a.grantee = 0 THEN 'PUBLIC' ELSE pg_get_userbyid(a.grantee) END AS grantee,
  a.privilege_type,
  a.is_grantable
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace
LEFT JOIN LATERAL aclexplode(coalesce(c.relacl, acldefault('s', c.relowner))) a ON TRUE
WHERE n.nspname = 'research' AND c.relkind = 'S'
ORDER BY n.nspname COLLATE "C", c.relname COLLATE "C",
         coalesce(CASE WHEN a.grantee = 0 THEN 'PUBLIC'
                       ELSE pg_get_userbyid(a.grantee) END, '') COLLATE "C",
         coalesce(a.privilege_type, '') COLLATE "C";


-- =====================================================================
-- G15 — TRIGGERS                                   EV-TRIGGER-001
-- =====================================================================
-- Replaces Revision 7's "exact schema-8 trigger set" (which supplied no set).
-- Internal constraint triggers are flagged, not dropped, so the distinction
-- is provable.
-- Row key: schema.table.trigger
SELECT
  'EV-TRIGGER-001'                                  AS evidence_set,
  n.nspname || '.' || c.relname || '.' || tg.tgname AS row_key,
  n.nspname                                         AS schema_name,
  c.relname                                         AS table_name,
  tg.tgname                                         AS trigger_name,
  tg.tgenabled,
  tg.tgisinternal                                   AS is_internal,
  pf.proname                                        AS trigger_function,
  pn.nspname                                        AS trigger_function_schema,
  pg_get_triggerdef(tg.oid, true)                   AS trigger_definition,
  md5(pg_get_triggerdef(tg.oid, true))              AS trigger_definition_md5
FROM pg_trigger tg
JOIN pg_class c      ON c.oid = tg.tgrelid
JOIN pg_namespace n  ON n.oid = c.relnamespace
JOIN pg_proc pf      ON pf.oid = tg.tgfoid
JOIN pg_namespace pn ON pn.oid = pf.pronamespace
WHERE n.nspname = 'research'
ORDER BY n.nspname COLLATE "C", c.relname COLLATE "C", tg.tgname COLLATE "C";


-- =====================================================================
-- G16 — ROW SECURITY POLICIES                      EV-POLICY-001
-- =====================================================================
-- Row key: schema.table.policy
SELECT
  'EV-POLICY-001'                                   AS evidence_set,
  n.nspname || '.' || c.relname || '.' || pol.polname AS row_key,
  n.nspname                                         AS schema_name,
  c.relname                                         AS table_name,
  pol.polname                                       AS policy_name,
  pol.polcmd,
  pol.polpermissive,
  coalesce((SELECT string_agg(pg_get_userbyid(x), ',' ORDER BY pg_get_userbyid(x) COLLATE "C")
            FROM unnest(pol.polroles) AS x), 'PUBLIC') AS applies_to_roles,
  coalesce(pg_get_expr(pol.polqual,      pol.polrelid), '\N') AS using_expr,
  coalesce(pg_get_expr(pol.polwithcheck, pol.polrelid), '\N') AS with_check_expr
FROM pg_policy pol
JOIN pg_class c     ON c.oid = pol.polrelid
JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE n.nspname = 'research'
ORDER BY n.nspname COLLATE "C", c.relname COLLATE "C", pol.polname COLLATE "C";


-- =====================================================================
-- G17 — CONSTRAINTS AND INDEXES                    EV-CONSTRAINT-001 / -002
-- =====================================================================
-- Supplies the literal constraint names that Revision 7 §13.8 refers to as
-- "constraints named exactly" without naming them.
-- Row key: schema.table.constraint
SELECT
  'EV-CONSTRAINT-001'                               AS evidence_set,
  n.nspname || '.' || c.relname || '.' || con.conname AS row_key,
  n.nspname                                         AS schema_name,
  c.relname                                         AS table_name,
  con.conname                                       AS constraint_name,
  con.contype,                                      -- c p u f t x
  con.condeferrable,
  con.convalidated,
  pg_get_constraintdef(con.oid, true)               AS constraint_definition,
  md5(pg_get_constraintdef(con.oid, true))          AS constraint_definition_md5
FROM pg_constraint con
JOIN pg_class c     ON c.oid = con.conrelid
JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE n.nspname = 'research'
ORDER BY n.nspname COLLATE "C", c.relname COLLATE "C", con.conname COLLATE "C";

-- Row key: schema.index
SELECT
  'EV-CONSTRAINT-002'                               AS evidence_set,
  n.nspname || '.' || ic.relname                    AS row_key,
  n.nspname                                         AS schema_name,
  tc.relname                                        AS table_name,
  ic.relname                                        AS index_name,
  i.indisunique,
  i.indisprimary,
  i.indisvalid,
  pg_get_indexdef(i.indexrelid, 0, true)            AS index_definition,
  md5(pg_get_indexdef(i.indexrelid, 0, true))       AS index_definition_md5
FROM pg_index i
JOIN pg_class ic    ON ic.oid = i.indexrelid
JOIN pg_class tc    ON tc.oid = i.indrelid
JOIN pg_namespace n ON n.oid = tc.relnamespace
WHERE n.nspname = 'research'
ORDER BY n.nspname COLLATE "C", ic.relname COLLATE "C";


-- =====================================================================
-- G18 — DEFAULT PRIVILEGES                         EV-DEFACL-001
-- =====================================================================
-- *** LOAD-BEARING FOR CODEX FINDING #2. ***
-- An ALTER DEFAULT PRIVILEGES rule applies ONLY to objects created BY the
-- role it targets (defaclrole). Revision 7 infers research_app DELETE from a
-- default-privilege rule in migration 002 without demonstrating that each
-- table was created by that same role. defaclrole here is the fact that
-- settles it, cross-referenced against relowner from G09.
-- defaclobjtype: r=table  S=sequence  f=function  T=type  n=schema
-- Row key: defaclrole|schema|objtype|grantee|privilege
SELECT
  'EV-DEFACL-001'                                   AS evidence_set,
  pg_get_userbyid(d.defaclrole)
    || '|' || coalesce(n.nspname, '<ALL_SCHEMAS>')
    || '|' || d.defaclobjtype
    || '|' || coalesce(CASE WHEN a.grantee = 0 THEN 'PUBLIC'
                            ELSE pg_get_userbyid(a.grantee) END, '\N')
    || '|' || coalesce(a.privilege_type, '\N')      AS row_key,
  pg_get_userbyid(d.defaclrole)                     AS target_owner_role,
  coalesce(n.nspname, '<ALL_SCHEMAS>')              AS schema_name,
  d.defaclobjtype                                   AS object_type,
  CASE WHEN a.grantee = 0 THEN 'PUBLIC' ELSE pg_get_userbyid(a.grantee) END AS grantee,
  a.privilege_type,
  a.is_grantable
FROM pg_default_acl d
LEFT JOIN pg_namespace n ON n.oid = d.defaclnamespace
LEFT JOIN LATERAL aclexplode(d.defaclacl) a ON TRUE
ORDER BY 2 COLLATE "C", 3 COLLATE "C", 4 COLLATE "C",
         coalesce(5, '') COLLATE "C", coalesce(6, '') COLLATE "C";

-- Which tables were actually created by a role that has a default-privilege
-- rule? Any table whose owner has NO matching rule falsifies the inference.
-- Row key: schema.table
SELECT
  'EV-DEFACL-002'                                   AS evidence_set,
  n.nspname || '.' || c.relname                     AS row_key,
  c.relname                                         AS table_name,
  pg_get_userbyid(c.relowner)                       AS table_owner,
  EXISTS (SELECT 1 FROM pg_default_acl d
          WHERE d.defaclrole = c.relowner
            AND d.defaclobjtype = 'r'
            AND (d.defaclnamespace = n.oid OR d.defaclnamespace = 0)) AS owner_has_defacl_rule
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE n.nspname = 'research' AND c.relkind IN ('r', 'p')
ORDER BY 2 COLLATE "C";


-- =====================================================================
-- G19 — SAFETY BASELINE: STRUCTURAL DISCOVERY      EV-BASELINE-DISCOVERY
-- =====================================================================
-- Query groups 19 and 20 need application table and column names that this
-- SQL does NOT assume. Inventing them is precisely the Revision 7 failure.
-- These two discovery queries enumerate what exists; the executor fills the
-- templates in G20 from their output and records the mapping.
--
-- Every table in `research` with its live row count.
-- count(*) is bounded by statement_timeout; these are small governance tables.
-- Row key: schema.table
SELECT
  'EV-BASELINE-DISCOVERY-001'                       AS evidence_set,
  n.nspname || '.' || c.relname                     AS row_key,
  c.relname                                         AS table_name,
  (xpath('/row/c/text()',
     query_to_xml(format('SELECT count(*) AS c FROM %I.%I', n.nspname, c.relname),
                  false, true, '')))[1]::text::bigint AS live_row_count
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE n.nspname = 'research' AND c.relkind IN ('r', 'p')
ORDER BY 2 COLLATE "C";

-- Columns whose names suggest safety-baseline or SECRET material.
-- secret_risk = true means the column MUST NOT appear in any G20 SELECT.
-- This query reads column NAMES from the catalog only; it reads no values.
-- Row key: schema.table.column
SELECT
  'EV-BASELINE-DISCOVERY-002'                       AS evidence_set,
  n.nspname || '.' || c.relname || '.' || att.attname AS row_key,
  c.relname                                         AS table_name,
  att.attname                                       AS column_name,
  format_type(att.atttypid, att.atttypmod)          AS data_type,
  (att.attname ~* '(secret|token|api_?key|password|passwd|private_?key|cipher|encrypted|credential_value|plaintext)')
                                                    AS secret_risk,
  (att.attname ~* '(enabled|active|status|state|cost|usd|amount|price|token_count|tokens|count|version|approved|authorized)')
                                                    AS baseline_candidate
FROM pg_class c
JOIN pg_namespace n   ON n.oid = c.relnamespace
JOIN pg_attribute att ON att.attrelid = c.oid
WHERE n.nspname = 'research' AND c.relkind IN ('r', 'p')
  AND att.attnum > 0 AND NOT att.attisdropped
  AND (att.attname ~* '(secret|token|api_?key|password|passwd|private_?key|cipher|encrypted|credential|plaintext|enabled|active|status|state|cost|usd|amount|price|tokens|version|approved|authorized|workflow|envelope|provider|model|proposal)')
ORDER BY 3 COLLATE "C", att.attnum;


-- =====================================================================
-- G20 — SAFETY BASELINE / RESERVATION STATE / CUTOVER STATE
--       *** TEMPLATE — REQUIRES G19 OUTPUT — DO NOT GUESS NAMES ***
-- =====================================================================
-- Fill each <<PLACEHOLDER>> from EV-BASELINE-DISCOVERY-001/002 and record
-- the substitution in the evidence manifest. If a placeholder has no
-- discovered counterpart, return BLOCKED_MISSING_CATALOG_DETAIL naming it.
-- Do NOT substitute a plausible name.
--
-- SECRET RULE: every column listed in a SELECT below must have
-- secret_risk = false in EV-BASELINE-DISCOVERY-002. No SELECT *, ever.
--
-- -- EV-BASELINE-002  schema version
-- SELECT 'EV-BASELINE-002' AS evidence_set,
--        <<VERSION_COLUMN>> AS schema_version
-- FROM research.<<VERSION_TABLE>>;
--
-- -- EV-BASELINE-003  provider / model enablement
-- SELECT 'EV-BASELINE-003' AS evidence_set,
--        <<PROVIDER_ID_COLUMN>> AS provider_id,
--        <<ENABLED_COLUMN>>     AS enabled
-- FROM research.<<PROVIDER_TABLE>>
-- ORDER BY 2 COLLATE "C";
--
-- -- EV-BASELINE-004  credential status, NON-SECRET FIELDS ONLY
-- SELECT 'EV-BASELINE-004' AS evidence_set,
--        <<CREDENTIAL_ID_COLUMN>>     AS credential_id,
--        <<CREDENTIAL_STATUS_COLUMN>> AS status,
--        <<PROVIDER_FK_COLUMN>>       AS provider_ref
-- FROM research.<<CREDENTIAL_TABLE>>
-- ORDER BY 2 COLLATE "C";
--
-- -- EV-BASELINE-005  zero-activity assertions
-- SELECT 'EV-BASELINE-005' AS evidence_set, 'approvals'   AS metric, count(*) FROM research.<<PROPOSAL_TABLE>>      WHERE <<APPROVED_PREDICATE>>
-- UNION ALL SELECT 'EV-BASELINE-005','activations',        count(*) FROM research.<<AUTHORIZATION_TABLE>> WHERE <<ACTIVE_PREDICATE>>
-- UNION ALL SELECT 'EV-BASELINE-005','active_workflows',   count(*) FROM research.<<WORKFLOW_TABLE>>      WHERE <<ACTIVE_PREDICATE>>
-- UNION ALL SELECT 'EV-BASELINE-005','request_envelopes',  count(*) FROM research.<<ENVELOPE_TABLE>>
-- UNION ALL SELECT 'EV-BASELINE-005','live_calls',         count(*) FROM research.<<LEDGER_TABLE>>
-- ORDER BY 2 COLLATE "C";
--
-- -- EV-BASELINE-006  paid usage must be exactly 0.00
-- SELECT 'EV-BASELINE-006' AS evidence_set,
--        coalesce(sum(<<COST_COLUMN>>), 0)::numeric(18,2) AS paid_usage_usd
-- FROM research.<<LEDGER_TABLE>>;
--
-- -- EV-RESERVATION-001  State A / B / C determination.
-- -- A = original present, legacy absent;  B = legacy present, original absent
-- -- C = both present OR neither present -> failed_frozen, owner intervention
-- SELECT 'EV-RESERVATION-001' AS evidence_set,
--        to_regclass('research.<<ORIGINAL_RESERVATION_TABLE>>') IS NOT NULL AS original_exists,
--        to_regclass('research.<<LEGACY_RESERVATION_TABLE>>')   IS NOT NULL AS legacy_exists,
--        CASE
--          WHEN to_regclass('research.<<ORIGINAL_RESERVATION_TABLE>>') IS NOT NULL
--           AND to_regclass('research.<<LEGACY_RESERVATION_TABLE>>')   IS NULL THEN 'A'
--          WHEN to_regclass('research.<<ORIGINAL_RESERVATION_TABLE>>') IS NULL
--           AND to_regclass('research.<<LEGACY_RESERVATION_TABLE>>')   IS NOT NULL THEN 'B'
--          ELSE 'C'
--        END AS reservation_state;
--
-- -- EV-CUTOVER-001  existing cutover-state rows
-- SELECT 'EV-CUTOVER-001' AS evidence_set, <<CUTOVER_COLUMNS>>
-- FROM research.<<CUTOVER_STATE_TABLE>>
-- ORDER BY 2 COLLATE "C";


-- =====================================================================
-- G99 — DRIFT DIGEST (END)                         EV-DRIFT-002
-- =====================================================================
-- MUST equal EV-DRIFT-001. If it differs, the catalog changed during
-- capture: the pack is void and must be recaptured under quiescence.
SELECT
  'EV-DRIFT-002'                                    AS evidence_set,
  'end'                                             AS position,
  encode(sha256(convert_to(
    coalesce(string_agg(x, chr(30) ORDER BY x COLLATE "C"), ''), 'UTF8')), 'hex') AS drift_digest
FROM (
  SELECT 'c' || chr(31) || c.relname || chr(31) || coalesce(c.relacl::text, '\N') AS x
  FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'research'
  UNION ALL
  SELECT 'p' || chr(31) || p.proname || chr(31)
         || pg_get_function_identity_arguments(p.oid) || chr(31)
         || coalesce(p.proacl::text, '\N')
  FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
  WHERE n.nspname = 'research'
  UNION ALL
  SELECT 'n' || chr(31) || n.nspname || chr(31) || coalesce(n.nspacl::text, '\N')
  FROM pg_namespace n WHERE n.nspname = 'research'
) t;


ROLLBACK;
-- =====================================================================
-- END OF BUNDLE. Safe to execute repeatedly; leaves no trace.
-- =====================================================================
