"""Shared models and stable error codes for Self-Improvement Loop V2."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

SCHEMA_VERSION = "2.0.0"

SUCCESS_STATES = (
    "CANDIDATE_RECEIVED",
    "RESEARCH_VALIDATED",
    "PROPOSAL_VALIDATED",
    "PROPOSAL_FROZEN",
    "RISK_CLASSIFIED",
    "AUTO_AUTHORIZED",
    "DETACHED_WORKTREE_PREPARED",
    "PATCH_APPLIED",
    "EXECUTION_BUNDLE_FROZEN",
    "VALIDATING",
    "REVIEW_PENDING",
    "REVIEW_BOUND",
    "FINALIZATION_REVALIDATED",
    "CANDIDATE_COMMITTED",
    "LEARNING_RECORDED",
    "READY_FOR_HUMAN_PROMOTION",
)

FAILURE_STATES = (
    "DECISION_REQUIRED",
    "BASELINE_MISMATCH",
    "POLICY_REJECTED",
    "PATCH_REJECTED",
    "VALIDATION_FAILED",
    "REVIEW_FAILED",
    "CONTENT_BINDING_MISMATCH",
    "IMMUTABILITY_VIOLATION",
    "REPAIR_LIMIT_REACHED",
    "FAILED_FROZEN",
)

ERROR_CODES = {
    "BASELINE_MISMATCH": "BASELINE_MISMATCH",
    "DIRTY_SOURCE_TREE": "DIRTY_SOURCE_TREE",
    "CONTENT_BINDING_MISMATCH": "CONTENT_BINDING_MISMATCH",
    "IMMUTABILITY_VIOLATION": "SI2-STORE-IMMUTABILITY",
    "SI2-STORE-IMMUTABILITY": "SI2-STORE-IMMUTABILITY",
    "SI2-PATH-ABSOLUTE": "SI2-PATH-ABSOLUTE",
    "SI2-PATH-TRAVERSAL": "SI2-PATH-TRAVERSAL",
    "SI2-PATH-PROTECTED-SEGMENT": "SI2-PATH-PROTECTED-SEGMENT",
    "SI2-PATH-PROTECTED-BASENAME": "SI2-PATH-PROTECTED-BASENAME",
    "SI2-PATH-FORBIDDEN-ROOT": "SI2-PATH-FORBIDDEN-ROOT",
    "SI2-PATH-SYMLINK": "SI2-PATH-SYMLINK",
    "SI2-PATH-SUBMODULE": "SI2-PATH-SUBMODULE",
    "SI2-PATH-QUOTED-UNSAFE": "SI2-PATH-QUOTED-UNSAFE",
    "SI2-REVIEW-SELF": "SI2-REVIEW-SELF",
    "SI2-REVIEW-PROPOSAL-HASH": "SI2-REVIEW-PROPOSAL-HASH",
    "SI2-REVIEW-EXECUTION-ID": "SI2-REVIEW-EXECUTION-ID",
    "SI2-REVIEW-EXECUTION-HASH": "SI2-REVIEW-EXECUTION-HASH",
    "SI2-REVIEW-DIFF-HASH": "SI2-REVIEW-DIFF-HASH",
    "SI2-REVIEW-TREE-HASH": "SI2-REVIEW-TREE-HASH",
    "SI2-REVIEW-VALIDATION-HASH": "SI2-REVIEW-VALIDATION-HASH",
    "SI2-REVIEW-FINDINGS": "SI2-REVIEW-FINDINGS",
    "SI2-REVIEW-MISSING": "SI2-REVIEW-MISSING",
    "SI2-REVIEW-CONFLICT": "SI2-REVIEW-CONFLICT",
    "SI2-REVIEW-RISK-BINDING": "SI2-REVIEW-RISK-BINDING",
    "BINARY_PATCH": "BINARY_PATCH",
    "DELETION_PROHIBITED": "DELETION_PROHIBITED",
    "RENAME_PROHIBITED": "RENAME_PROHIBITED",
    "COPY_PROHIBITED": "COPY_PROHIBITED",
    "PREIMAGE_MISMATCH": "PREIMAGE_MISMATCH",
    "POSTIMAGE_MISMATCH": "POSTIMAGE_MISMATCH",
    "TOO_MANY_FILES": "TOO_MANY_FILES",
    "EXCESSIVE_DIFF": "EXCESSIVE_DIFF",
    "EXCESSIVE_PATCH_SIZE": "EXCESSIVE_PATCH_SIZE",
    "PROHIBITED_VALIDATION_PROFILE": "PROHIBITED_VALIDATION_PROFILE",
    "COMMAND_INJECTION": "COMMAND_INJECTION",
    "VALIDATION_TIMEOUT": "VALIDATION_TIMEOUT",
    "ACCEPTANCE_FAILED": "ACCEPTANCE_FAILED",
    "REPAIR_LIMIT_REACHED": "REPAIR_LIMIT_REACHED",
    "COMMIT_BEFORE_REVIEW": "COMMIT_BEFORE_REVIEW",
    "BRANCH_BEFORE_REVIEW": "BRANCH_BEFORE_REVIEW",
    "SOURCE_REPO_CHANGED": "SOURCE_REPO_CHANGED",
    "CREDENTIALS_IN_WORKFLOW": "CREDENTIALS_IN_WORKFLOW",
    "WORKFLOW_ACTIVE": "WORKFLOW_ACTIVE",
    "PUSH_ATTEMPT": "PUSH_ATTEMPT",
    "MERGE_ATTEMPT": "MERGE_ATTEMPT",
    "POLICY_REJECTED": "POLICY_REJECTED",
    "PATCH_REJECTED": "PATCH_REJECTED",
    "VALIDATION_FAILED": "VALIDATION_FAILED",
    "REVIEW_FAILED": "REVIEW_FAILED",
    "FAILED_FROZEN": "FAILED_FROZEN",
    "SYMLINK_PROHIBITED": "SI2-PATH-SYMLINK",
    "SUBMODULE_CHANGE": "SI2-PATH-SUBMODULE",
    "GIT_APPLY_CHECK_FAILED": "GIT_APPLY_CHECK_FAILED",
    "SCHEMA_INVALID": "SCHEMA_INVALID",
    "RISK_NOT_AUTO_AUTHORIZED": "RISK_NOT_AUTO_AUTHORIZED",
    "RISK_ESCALATED_POST_EXECUTION": "RISK_ESCALATED_POST_EXECUTION",
    "RISK_AUTH_REPLAY": "RISK_AUTH_REPLAY",
    "RISK_EVIDENCE_MISSING": "RISK_EVIDENCE_MISSING",
    "RISK_POLICY_BINDING": "RISK_POLICY_BINDING",
    "RISK_POLICY_TIGHTENED": "RISK_POLICY_TIGHTENED",
    "REPAIR_BROADENING": "REPAIR_BROADENING",
    "SI2-WF-MISSING-FAILURE-EDGE": "SI2-WF-MISSING-FAILURE-EDGE",
    "SI2-WF-INVALID-RISK-ROUTE": "SI2-WF-INVALID-RISK-ROUTE",
    "SI2-WF-DISCONNECTED-FAILURE-STATE": "SI2-WF-DISCONNECTED-FAILURE-STATE",
    "SI2-WF-MARKER-NOT-ROUTE": "SI2-WF-MARKER-NOT-ROUTE",
    "SI2-WF-AUTOAUTH-NONLOW": "SI2-WF-AUTOAUTH-NONLOW",
    "SI2-GIT-HOOKS-NOT-ISOLATED": "SI2-GIT-HOOKS-NOT-ISOLATED",
    "SI2-GIT-SIGNING-NOT-DISABLED": "SI2-GIT-SIGNING-NOT-DISABLED",
    "SI2-GIT-CONFIG-MUTATION": "SI2-GIT-CONFIG-MUTATION",
    "SI2-FINALIZE-PROPOSAL-HASH": "SI2-FINALIZE-PROPOSAL-HASH",
    "SI2-PATH-SPOOFED-PROTECTED-NAME": "SI2-PATH-SPOOFED-PROTECTED-NAME",
    "SI2-STORE-DATABASE-IMMUTABILITY": "SI2-STORE-DATABASE-IMMUTABILITY",
    "SI2-AGENT-RUNTIME-CONTRACT": "SI2-AGENT-RUNTIME-CONTRACT",
    "PILOT_BUDGET_EXCEEDED": "PILOT_BUDGET_EXCEEDED",
    "PILOT_BUDGET_INVALID": "PILOT_BUDGET_INVALID",
    "PILOT_CALL_LIMIT": "PILOT_CALL_LIMIT",
    "PILOT_COST_BOUND": "PILOT_COST_BOUND",
    "PILOT_WALL_CLOCK": "PILOT_WALL_CLOCK",
    "PILOT_PERMIT_INVALID": "PILOT_PERMIT_INVALID",
    "PILOT_PERMIT_CONSUMED": "PILOT_PERMIT_CONSUMED",
    "PILOT_PERMIT_NOT_CONSUMED": "PILOT_PERMIT_NOT_CONSUMED",
    "TRUSTED_ORIGIN_VIOLATION": "TRUSTED_ORIGIN_VIOLATION",
    "WALL_REASSERT_MISMATCH": "WALL_REASSERT_MISMATCH",
    "WORKFLOW_NORMALIZER": "WORKFLOW_NORMALIZER",
    "ZONE_P_HARNESS": "ZONE_P_HARNESS",
    "MODEL_RESOLUTION_PROBE": "MODEL_RESOLUTION_PROBE",
    "CACHED_TOPOLOGY_AUTHORITY": "CACHED_TOPOLOGY_AUTHORITY",
    "DOCKER_PREFIX_ID": "DOCKER_PREFIX_ID",
    "TOPOLOGY_REASSERT_FAILED": "TOPOLOGY_REASSERT_FAILED",
    "ATTESTATION_EXISTS": "ATTESTATION_EXISTS",
    "ATTESTATION_INCOMPLETE": "ATTESTATION_INCOMPLETE",
    "SEAL_BIND_MISMATCH": "SEAL_BIND_MISMATCH",
    "EXTRA_ARTIFACT": "EXTRA_ARTIFACT",
    "MISSING_ARTIFACT": "MISSING_ARTIFACT",
    "NON_REGULAR_ARTIFACT": "NON_REGULAR_ARTIFACT",
    "COPIED_GENERATION_INVALID": "COPIED_GENERATION_INVALID",
    "HOST_TMP_SRL_EXEC": "HOST_TMP_SRL_EXEC",
    "UNGUARDED_GIT": "UNGUARDED_GIT",
    "REVIEWED_SOURCE_WRITE": "REVIEWED_SOURCE_WRITE",
    "UNSAFE_CLEANUP_TARGET": "UNSAFE_CLEANUP_TARGET",
    "EXECUTION_ID_GRAMMAR": "EXECUTION_ID_GRAMMAR",
    "FORGED_EXPORT": "FORGED_EXPORT",
    "RUNTIME_MODE_NOT_AUTHORITY": "RUNTIME_MODE_NOT_AUTHORITY",
    "FORBIDDEN_GIT_OP": "FORBIDDEN_GIT_OP",
    "AUTHORITY_C_OMITTED": "AUTHORITY_C_OMITTED",
    "AUTHORITY_C_FAILED": "AUTHORITY_C_FAILED",
}


@dataclass
class WorkerError(Exception):
    code: str
    message: str
    state: str = "FAILED_FROZEN"

    def __str__(self) -> str:
        return f"{self.code}: {self.message}"


@dataclass
class ExecutionHandle:
    execution_id: str
    worktree_path: str
    source_root: str
    baseline_sha: str
    meta: dict[str, Any] = field(default_factory=dict)
