#!/usr/bin/env python3
"""Deterministic Round 5A generated documentation (non-normative)."""
from __future__ import annotations

import argparse
import ast
import hashlib
import json
import os
import re
import sys
import tempfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

GENERATOR_NAME = "generate_round5a_docs"
GENERATOR_VERSION = "1.1.0"

BANNER = """AUTOGENERATED — DO NOT EDIT MANUALLY

Normative authority:
- specs/round5a/catalog_contract.yaml
- specs/round5a/checkpoints.yaml
- specs/round5a/reconciliation_rules.yaml
- specs/round5a/evidence_aliases.yaml
- specs/round5a/fixtures/*.yaml

Generated documentation is non-normative.
When generated text conflicts with a registry, the registry controls.
"""

OUTPUT_REL_PATHS = [
    "docs/generated/round5a/ARCHITECTURE.md",
    "docs/generated/round5a/VERIFICATION.md",
    "docs/generated/round5a/TRACEABILITY.md",
    "docs/generated/round5a/generation_manifest.json",
]

NORMATIVE_HASH_PATHS = [
    "specs/round5a/catalog_contract.yaml",
    "specs/round5a/checkpoints.yaml",
    "specs/round5a/reconciliation_rules.yaml",
    "specs/round5a/evidence_aliases.yaml",
    "specs/round5a/registry_manifest.yaml",
    "specs/round5a/schema/round5a_registry.schema.json",
    "specs/round5a/fixtures/reconciliation_witnesses.yaml",
    "specs/round5a/fixtures/checkpoint_oracles.yaml",
    "specs/round5a/fixtures/privilege_cases.yaml",
]

SOURCE_LOAD_PATHS = [
    "specs/round5a/schema/round5a_registry.schema.json",
    "specs/round5a/SCHEMA_CONTRACT.md",
    "specs/round5a/catalog_contract.yaml",
    "specs/round5a/checkpoints.yaml",
    "specs/round5a/reconciliation_rules.yaml",
    "specs/round5a/evidence_aliases.yaml",
    "specs/round5a/registry_manifest.yaml",
    "specs/round5a/fixtures/reconciliation_witnesses.yaml",
    "specs/round5a/fixtures/checkpoint_oracles.yaml",
    "specs/round5a/fixtures/privilege_cases.yaml",
]

PRIV_PATH_DISPLAY = {
    "direct": "direct",
    "public": "PUBLIC",
    "inherited": "inherited",
    "set_role_only": "SET ROLE-only",
    "owner_derived": "owner-derived",
    "superuser_derived": "superuser-derived",
    "schema_gated": "schema-gated",
    "exercisable": "exercisable",
}

ABS_PATH_RE = re.compile(
    r"(?i)(?:[A-Za-z]:\\|\\\\|/tmp/|/var/|/home/|/Users/|AppData|Local\\\\Temp|TEMP\\|TMP\\)"
)
TIMESTAMP_RE = re.compile(
    r"\b20\d{2}-\d{2}-\d{2}(?:[T ]\d{2}:\d{2}:\d{2}(?:Z|[+-]\d{2}:\d{2})?)?\b"
)


@dataclass
class GenError:
    code: str
    message: str
    artifact: str = ""
    record: str = ""

    def as_dict(self) -> dict[str, str]:
        return {
            "code": self.code,
            "message": self.message,
            "artifact": self.artifact,
            "record": self.record,
        }


@dataclass
class GenResult:
    status: str = "PASS"
    errors: list[GenError] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    counts: dict[str, Any] = field(default_factory=dict)
    created: list[str] = field(default_factory=list)
    updated: list[str] = field(default_factory=list)
    unchanged: list[str] = field(default_factory=list)
    drift: list[dict[str, str]] = field(default_factory=list)
    outputs: dict[str, str] = field(default_factory=dict)

    def fail(self, err: GenError) -> None:
        self.status = "FAIL"
        self.errors.append(err)

    def as_dict(self) -> dict[str, Any]:
        return {
            "generator_name": GENERATOR_NAME,
            "generator_version": GENERATOR_VERSION,
            "final_status": self.status,
            "errors": [e.as_dict() for e in sorted(self.errors, key=lambda e: (e.code, e.artifact, e.record, e.message))],
            "warnings": sorted(self.warnings),
            "counts": dict(sorted(self.counts.items())),
            "created": sorted(self.created),
            "updated": sorted(self.updated),
            "unchanged": sorted(self.unchanged),
            "drift": sorted(self.drift, key=lambda d: d.get("file", "")),
            "output_hashes": {k: self.outputs[k] for k in sorted(self.outputs)},
        }


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def sha256_file(path: Path) -> str:
    return sha256_file_bytes(path.read_bytes())


def sha256_file_bytes(data: bytes) -> str:
    return sha256_bytes(data)


def utf8_lf(text: str) -> bytes:
    if not text.endswith("\n"):
        text += "\n"
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    return text.encode("utf-8")


def json_dump(obj: Any) -> bytes:
    return utf8_lf(json.dumps(obj, indent=2, sort_keys=False, ensure_ascii=False))


def load_json_compatible(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def confine(root: Path, rel: str) -> Path:
    root = root.resolve()
    candidate = (root / rel).resolve()
    try:
        candidate.relative_to(root)
    except ValueError as exc:
        raise ValueError(f"path escapes root: {rel}") from exc
    if candidate.is_symlink():
        raise ValueError(f"symlink rejected: {rel}")
    return candidate


def sanitize_text(value: Any) -> str:
    """Render values for generated docs without absolute/TEMP/user paths."""
    if value is None:
        return ""
    if isinstance(value, (dict, list)):
        text = json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False)
    else:
        text = str(value)
    text = text.replace("\\", "/")
    # Drop absolute / TEMP / username-bearing fragments while keeping relative docs/specs refs.
    parts = []
    for fragment in re.split(r"[;\n]", text):
        frag = fragment.strip()
        if not frag:
            continue
        if ABS_PATH_RE.search(frag):
            continue
        if "/Users/" in frag or "/home/" in frag:
            continue
        parts.append(frag)
    cleaned = "; ".join(parts) if parts else ""
    cleaned = TIMESTAMP_RE.sub("<redacted-timestamp>", cleaned)
    return cleaned


def md_escape(s: str) -> str:
    return s.replace("|", "\\|").replace("\n", " ")


def render_json_block(obj: Any) -> str:
    return "```json\n" + json.dumps(obj, indent=2, sort_keys=True, ensure_ascii=False) + "\n```"


def render_predicate(node: Any) -> str:
    return render_json_block(node)


def collect_nd_refs(obj: Any, acc: set[str]) -> None:
    if isinstance(obj, dict):
        for k, v in obj.items():
            if k in {"decision_refs", "nd_refs"} and isinstance(v, list):
                for item in v:
                    if isinstance(item, str) and item.startswith("ND-"):
                        acc.add(item)
            collect_nd_refs(v, acc)
    elif isinstance(obj, list):
        for item in obj:
            collect_nd_refs(item, acc)
    elif isinstance(obj, str) and obj.startswith("ND-"):
        acc.add(obj)


def collect_ev_refs(obj: Any, acc: set[str]) -> None:
    if isinstance(obj, dict):
        for k, v in obj.items():
            if k in {"evidence_refs"} and isinstance(v, list):
                for item in v:
                    if isinstance(item, str) and item.startswith("EV-"):
                        acc.add(item)
            if k in {"marker_identity"} and isinstance(v, str) and v.startswith("EV-"):
                acc.add(v)
            collect_ev_refs(v, acc)
    elif isinstance(obj, list):
        for item in obj:
            collect_ev_refs(item, acc)
    elif isinstance(obj, str) and obj.startswith("EV-"):
        acc.add(obj)


def marker_objects(catalog: dict[str, Any]) -> list[dict[str, Any]]:
    return [
        o
        for o in catalog["objects"]
        if str(o.get("attributes", {}).get("marker_id", "")).startswith("MARKER-")
    ]


def marker_value_status(attrs: dict[str, Any], evidence_class: str) -> str:
    raw = attrs.get("deterministic_reference_value")
    state = attrs.get("marker_state", "")
    if raw in (None, "", "UNKNOWN") or state.startswith("UNKNOWN_"):
        if evidence_class == "EXECUTION_TIME_LIVE_PREFLIGHT":
            return "unknown until live preflight (not a fact)"
        if evidence_class == "PILOT_TIME_RUNTIME_REVALIDATION":
            return "unknown until runtime revalidation (not a fact)"
        return "unknown (not a fact)"
    return f"reconstructed reference value: {sanitize_text(raw)}"


def required_gate(evidence_class: str) -> str:
    return {
        "RECONSTRUCTED_REFERENCE_SCHEMA8": "reconstructed reference",
        "EXECUTION_TIME_LIVE_PREFLIGHT": "live preflight",
        "PILOT_TIME_RUNTIME_REVALIDATION": "runtime revalidation",
        "NORMATIVE_DECISION_ONLY": "normative decision only",
    }.get(evidence_class, evidence_class)


def extract_test_inventory(test_path: Path) -> list[tuple[str, list[str]]]:
    tree = ast.parse(test_path.read_text(encoding="utf-8"))
    rows: list[tuple[str, list[str]]] = []
    for node in tree.body:
        if isinstance(node, ast.ClassDef):
            for item in node.body:
                if isinstance(item, ast.FunctionDef) and item.name.startswith("test_"):
                    codes = sorted(
                        {
                            n.value
                            for n in ast.walk(item)
                            if isinstance(n, ast.Constant)
                            and isinstance(n.value, str)
                            and n.value.startswith("R5A-")
                        }
                    )
                    rows.append((item.name, codes))
    rows.sort(key=lambda r: r[0])
    return rows


def run_phase_d_validator(root: Path) -> tuple[int, dict[str, Any]]:
    tools_dir = str((root / "tools").resolve())
    if tools_dir not in sys.path:
        sys.path.insert(0, tools_dir)
    import validate_round5a as validator  # noqa: WPS433

    fd, name = tempfile.mkstemp(prefix="r5a-gen-val-", suffix=".json")
    os.close(fd)
    report_path = Path(name)
    try:
        code = validator.main(["--root", str(root), "--report", str(report_path)])
        report = json.loads(report_path.read_text(encoding="utf-8"))
        return code, report
    finally:
        try:
            report_path.unlink(missing_ok=True)
        except OSError:
            pass


class Round5ADocGenerator:
    def __init__(self, root: Path):
        self.root = root.resolve()
        self.docs: dict[str, Any] = {}
        self.result = GenResult()
        self.schema_version = ""
        self.registry_version = ""
        self.source_hashes: dict[str, str] = {}
        self.markers: list[dict[str, Any]] = []
        self.checkpoints: list[dict[str, Any]] = []
        self.rules: list[dict[str, Any]] = []
        self.fixtures: list[dict[str, Any]] = []
        self.oracles: list[dict[str, Any]] = []
        self.privileges: list[dict[str, Any]] = []
        self.aliases: dict[str, Any] = {}
        self.nd_refs: set[str] = set()
        self.ev_refs: set[str] = set()
        self.primitives: set[str] = set()

    def load_sources(self) -> None:
        for rel in SOURCE_LOAD_PATHS:
            try:
                path = confine(self.root, rel)
            except ValueError as exc:
                self.result.fail(GenError("R5A-GEN-FILE-ESCAPE", str(exc), rel))
                return
            if not path.exists():
                self.result.fail(GenError("R5A-GEN-FILE-MISSING", f"missing source {rel}", rel))
                continue
            if path.suffix.lower() in {".yaml", ".json"}:
                try:
                    self.docs[rel] = load_json_compatible(path)
                except json.JSONDecodeError as exc:
                    self.result.fail(GenError("R5A-GEN-SOURCE-JSON", f"invalid JSON-compatible YAML: {exc}", rel))
                    continue
            self.source_hashes[rel] = sha256_file(path)

        if self.result.status != "PASS":
            return
        required_docs = [
            "specs/round5a/catalog_contract.yaml",
            "specs/round5a/checkpoints.yaml",
            "specs/round5a/reconciliation_rules.yaml",
            "specs/round5a/evidence_aliases.yaml",
            "specs/round5a/registry_manifest.yaml",
            "specs/round5a/fixtures/reconciliation_witnesses.yaml",
            "specs/round5a/fixtures/checkpoint_oracles.yaml",
            "specs/round5a/fixtures/privilege_cases.yaml",
        ]
        for rel in required_docs:
            if rel not in self.docs:
                self.result.fail(GenError("R5A-GEN-FILE-MISSING", f"required source not loaded: {rel}", rel))
        if self.result.status != "PASS":
            return

        catalog_doc = self.docs["specs/round5a/catalog_contract.yaml"]
        self.catalog = catalog_doc["catalog_contract"]
        self.aliases = self.docs["specs/round5a/evidence_aliases.yaml"]
        man = self.docs["specs/round5a/registry_manifest.yaml"]["registry_manifest"]
        self.schema_version = man.get("schema_version") or catalog_doc.get("schema_version") or "1.0.0"
        self.registry_version = man.get("registry_version") or "1.0.0"
        self.architecture_reset_name = man.get("architecture_reset_name") or "Round 5A Architecture Reset"
        self.markers = sorted(marker_objects(self.catalog), key=lambda o: o["attributes"]["marker_id"])
        self.checkpoints = sorted(
            self.docs["specs/round5a/checkpoints.yaml"]["checkpoint_registry"]["checkpoints"],
            key=lambda c: c["checkpoint_id"],
        )
        self.rules = sorted(
            self.docs["specs/round5a/reconciliation_rules.yaml"]["reconciliation_rule_registry"]["rules"],
            key=lambda r: r["order"],
        )
        self.fixtures = sorted(
            self.docs["specs/round5a/fixtures/reconciliation_witnesses.yaml"]["reconciliation_fixture_pack"]["fixtures"],
            key=lambda f: f["fixture_id"],
        )
        self.oracles = sorted(
            self.docs["specs/round5a/fixtures/checkpoint_oracles.yaml"]["checkpoint_oracle_pack"]["oracles"],
            key=lambda o: o["oracle_id"],
        )
        self.privileges = sorted(
            self.docs["specs/round5a/fixtures/privilege_cases.yaml"]["privilege_fixture_pack"]["fixtures"],
            key=lambda f: f["fixture_id"],
        )
        for blob in (
            catalog_doc,
            self.docs["specs/round5a/checkpoints.yaml"],
            self.docs["specs/round5a/reconciliation_rules.yaml"],
            self.docs["specs/round5a/fixtures/reconciliation_witnesses.yaml"],
            self.docs["specs/round5a/fixtures/checkpoint_oracles.yaml"],
            self.docs["specs/round5a/fixtures/privilege_cases.yaml"],
            self.docs["specs/round5a/registry_manifest.yaml"],
            self.docs["specs/round5a/evidence_aliases.yaml"],
        ):
            collect_nd_refs(blob, self.nd_refs)
            collect_ev_refs(blob, self.ev_refs)
        for o in self.catalog["objects"]:
            attrs = o.get("attributes") or {}
            for v in attrs.values():
                if isinstance(v, str) and v.startswith("PRIMITIVE-"):
                    self.primitives.add(v)
            sel = o.get("object_selector") or {}
            pref = sel.get("primitive_ref")
            if isinstance(pref, str) and pref.startswith("PRIMITIVE-"):
                self.primitives.add(pref)
        for c in self.checkpoints:
            pref = c.get("object_selector", {}).get("primitive_ref")
            if isinstance(pref, str):
                self.primitives.add(pref)
        rd = self.catalog.get("role_discovery") or {}
        if isinstance(rd.get("discovery_primitive_ref"), str):
            self.primitives.add(rd["discovery_primitive_ref"])

    def integrity(self, validator_report: dict[str, Any], validator_code: int) -> None:
        if validator_code != 0 or validator_report.get("final_status") != "PASS":
            self.result.fail(
                GenError(
                    "R5A-GEN-SOURCE-VALIDATOR",
                    f"Phase D validator not PASS (exit={validator_code}, status={validator_report.get('final_status')})",
                )
            )
            return

        man = self.docs["specs/round5a/registry_manifest.yaml"]["registry_manifest"]
        for entry in man["artifact_hashes"]:
            rel = entry["path"]
            try:
                path = confine(self.root, rel)
            except ValueError as exc:
                self.result.fail(GenError("R5A-GEN-MANIFEST-ESCAPE", str(exc), rel))
                continue
            if not path.exists():
                self.result.fail(GenError("R5A-GEN-MANIFEST-MISSING", f"manifest path missing: {rel}", rel))
                continue
            actual = sha256_file(path)
            if actual != entry["sha256"]:
                self.result.fail(
                    GenError(
                        "R5A-GEN-MANIFEST-HASH",
                        f"hash mismatch expected={entry['sha256']} actual={actual}",
                        rel,
                    )
                )

        recon = sum(1 for m in self.markers if m["provenance"]["evidence_class"] == "RECONSTRUCTED_REFERENCE_SCHEMA8")
        live = sum(1 for m in self.markers if m["provenance"]["evidence_class"] == "EXECUTION_TIME_LIVE_PREFLIGHT")
        runtime = sum(1 for m in self.markers if m["provenance"]["evidence_class"] == "PILOT_TIME_RUNTIME_REVALIDATION")
        if (len(self.markers), recon, live, runtime) != (31, 17, 11, 3):
            self.result.fail(
                GenError(
                    "R5A-GEN-SOURCE-COUNTS",
                    f"marker totals {len(self.markers)}/{recon}/{live}/{runtime} != 31/17/11/3",
                )
            )

        if len(self.checkpoints) != 18:
            self.result.fail(GenError("R5A-GEN-SOURCE-COUNTS", f"checkpoints={len(self.checkpoints)} != 18"))
        if len(self.rules) != 22 or [r["order"] for r in self.rules] != list(range(1, 23)):
            self.result.fail(GenError("R5A-GEN-SOURCE-COUNTS", "rules must be orders 1..22"))
        fallbacks = [r for r in self.rules if r.get("is_fallback")]
        if len(fallbacks) != 1 or fallbacks[0]["order"] != 22 or fallbacks[0].get("failure_state") != "failed_frozen":
            self.result.fail(GenError("R5A-GEN-SOURCE-FALLBACK", "fallback must be unique order 22 failed_frozen"))

        pos = [
            f
            for f in self.fixtures
            if f["fixture_kind"] in ("POSITIVE_WITNESS", "FALLBACK_WITNESS") and f["fixture_id"].startswith("FIXTURE-W")
        ]
        bounds = [f for f in self.fixtures if f["fixture_kind"] == "BOUNDARY_WITNESS"]
        pairs: set[tuple[int, int]] = set()
        for fx in pos:
            j = int(fx["expected_rule"].split("-")[1])
            for rid in fx.get("earlier_rules_expected_false") or []:
                pairs.add((int(rid.split("-")[1]), j))
        missing_w = [f"FIXTURE-W{i}" for i in range(1, 23) if not any(f["fixture_id"] == f"FIXTURE-W{i}" for f in pos)]
        missing_b = [f"FIXTURE-B{i}" for i in range(1, 22) if not any(f["fixture_id"] == f"FIXTURE-B{i}" for f in bounds)]
        if missing_w:
            self.result.fail(GenError("R5A-GEN-SOURCE-WITNESS", f"missing witnesses: {missing_w}"))
        if missing_b:
            self.result.fail(GenError("R5A-GEN-SOURCE-BOUNDARY", f"missing boundaries: {missing_b}"))
        if len(pairs) != 231:
            self.result.fail(GenError("R5A-GEN-SOURCE-SHADOW", f"shadowing_pairs={len(pairs)} != 231"))

        # Traceability resolve: every ND/EV/checkpoint/rule/fixture id must be referenceable
        cp_ids = {c["checkpoint_id"] for c in self.checkpoints}
        rule_ids = {r["rule_id"] for r in self.rules}
        marker_ids = {m["attributes"]["marker_id"] for m in self.markers}
        fixture_ids = {f["fixture_id"] for f in self.fixtures}
        oracle_ids = {o["oracle_id"] for o in self.oracles}
        priv_ids = {f["fixture_id"] for f in self.privileges}
        for fx in self.fixtures:
            if fx.get("expected_rule") and fx["expected_rule"] not in rule_ids:
                self.result.fail(GenError("R5A-GEN-TRACE-RULE", f"unresolved rule {fx['expected_rule']}", record=fx["fixture_id"]))
        for o in self.oracles:
            if o["checkpoint_ref"] not in cp_ids:
                self.result.fail(GenError("R5A-GEN-TRACE-CKP", f"unresolved checkpoint {o['checkpoint_ref']}", record=o["oracle_id"]))
        for c in self.checkpoints:
            mid = c.get("evidence_marker", {}).get("marker_id")
            if mid and mid not in marker_ids:
                self.result.fail(GenError("R5A-GEN-TRACE-MARKER", f"unresolved marker {mid}", record=c["checkpoint_id"]))

        self.result.counts.update(
            {
                "evidence_markers": len(self.markers),
                "reconstructed": recon,
                "live_preflight": live,
                "runtime_revalidation": runtime,
                "checkpoints": len(self.checkpoints),
                "rules": len(self.rules),
                "witnesses": len(pos),
                "boundaries": len(bounds),
                "shadowing_pairs": len(pairs),
                "oracles": len(oracle_ids),
                "privilege_fixtures": len(priv_ids),
                "fixtures_total": len(fixture_ids),
                "nd_refs": len(self.nd_refs),
                "ev_refs": len(self.ev_refs),
                "primitives": len(self.primitives),
            }
        )
        self._pos = pos
        self._bounds = bounds
        self._pairs = pairs
        self._muts = [f for f in self.fixtures if f["fixture_kind"] == "MUTATION_WITNESS"]
        self._maps = [f for f in self.fixtures if f["fixture_kind"] == "MAPPING_CASE"]
        self._state_a = [f for f in self.fixtures if f["fixture_kind"] == "STATE_A_CASE"]
        self._state_b = [f for f in self.fixtures if f["fixture_kind"] == "STATE_B_CASE"]

    def render_architecture(self) -> str:
        lines: list[str] = [BANNER.rstrip(), "", "# Round 5A Architecture Reset — Generated Architecture", ""]
        # 9.1
        lines += [
            "## 9.1 Authority and status",
            "",
            f"- Architecture reset name: {self.architecture_reset_name}",
            f"- Schema version: {self.schema_version}",
            f"- Registry version: {self.registry_version}",
            "- Normative source paths:",
        ]
        for rel in [
            "specs/round5a/catalog_contract.yaml",
            "specs/round5a/checkpoints.yaml",
            "specs/round5a/reconciliation_rules.yaml",
            "specs/round5a/evidence_aliases.yaml",
            "specs/round5a/registry_manifest.yaml",
            "specs/round5a/fixtures/reconciliation_witnesses.yaml",
            "specs/round5a/fixtures/checkpoint_oracles.yaml",
            "specs/round5a/fixtures/privilege_cases.yaml",
            "specs/round5a/schema/round5a_registry.schema.json",
        ]:
            lines.append(f"  - `{rel}` SHA-256 `{self.source_hashes[rel]}`")
        lines += [
            "- Evidence hierarchy: reconstructed reference → live preflight → runtime revalidation",
            "- Generated documentation is non-normative. Registries remain authoritative.",
            "- Schema-9 status: not implemented",
            "- Live preflight status: not executed",
            "- Runtime revalidation status: not executed",
            "",
            "## Evidence provenance",
            "",
            "### Bound sources",
            "",
            "- Current git-bound archived Phase 1 copy: `evidence/round5a/archived_phase1/`",
            "- Historical git authentication status: `UNVERIFIED`",
            "- Claimed historical commit `8d592bf` is not authenticated by hash equality",
            "- Recreated Phase 1 bundle: `evidence/round5a/recreated_phase1/`",
            "- Reconstructed-reference logical artifact ID: `ROUND5A-RECONSTRUCTED-REFERENCE-SCHEMA8`",
            "- Location policy: `RUNTIME_SUPPLIED_EXTERNAL_ARTIFACT`",
            "",
            "### Evidence hierarchy",
            "",
            "1. Human-approved ND / ND-PROV decisions",
            "2. Machine-readable registries including `evidence_aliases.yaml`",
            "3. Committed archived/recreated query producers (not catalog rows)",
            "4. Runtime-supplied reconstructed-reference external artifacts",
            "5. Generated Markdown (non-normative)",
            "",
            "### Warning",
            "",
            "Hash equality of offline archived bytes does **not** prove historical commit origin.",
            "Historical authentication remains `UNVERIFIED`.",
            "",
            "## 9.2 Evidence model",
            "",
            "### Evidence classes",
            "",
            "- RECONSTRUCTED_REFERENCE_SCHEMA8",
            "- EXECUTION_TIME_LIVE_PREFLIGHT",
            "- PILOT_TIME_RUNTIME_REVALIDATION",
            "- NORMATIVE_DECISION_ONLY",
            "",
            "### Marker-state definitions",
            "",
            "- RECONSTRUCTED_REFERENCE_ACCEPTED",
            "- UNKNOWN_UNTIL_LIVE_PREFLIGHT",
            "- UNKNOWN_UNTIL_RUNTIME_REVALIDATION",
            "",
            "### Comparison outcomes",
            "",
        ]
        outcomes = sorted(
            {
                part
                for m in self.markers
                for part in str(m["attributes"].get("comparison_outcomes", "")).split("|")
                if part
            }
        )
        for o in outcomes:
            lines.append(f"- {o}")
        fails = sorted({m["attributes"].get("failure_behavior", "") for m in self.markers if m["attributes"].get("failure_behavior")})
        lines += ["", "### Failure outcomes", ""]
        for f in fails:
            lines.append(f"- {f}")
        lines += [
            "",
            "### Exact marker recount",
            "",
            f"- Total markers: {self.result.counts['evidence_markers']}",
            f"- Reconstructed reference: {self.result.counts['reconstructed']}",
            f"- Live preflight: {self.result.counts['live_preflight']}",
            f"- Runtime revalidation: {self.result.counts['runtime_revalidation']}",
            "",
            "### Marker table",
            "",
            "| Marker | State | Evidence class | ND references | EV references | Current value status | Required gate | Failure behavior |",
            "| --- | --- | --- | --- | --- | --- | --- | --- |",
        ]
        for m in self.markers:
            a = m["attributes"]
            prov = m["provenance"]
            nd = ", ".join(sorted(prov.get("decision_refs") or []))
            ev = ", ".join(sorted(prov.get("evidence_refs") or a.get("marker_identity") and [a["marker_identity"]] or []))
            lines.append(
                "| "
                + " | ".join(
                    md_escape(x)
                    for x in [
                        a["marker_id"],
                        a.get("marker_state", ""),
                        prov["evidence_class"],
                        nd,
                        ev,
                        marker_value_status(a, prov["evidence_class"]),
                        required_gate(prov["evidence_class"]),
                        a.get("failure_behavior", ""),
                    ]
                )
                + " |"
            )

        # 9.3 Catalog
        rd = self.catalog["role_discovery"]
        lines += [
            "",
            "## 9.3 Catalog and role model",
            "",
            "### PostgreSQL assumptions",
            "",
            "- Role discovery mode is catalog discovery, not a fixed-role-only inventory.",
            "- Deny-by-default privilege posture is enabled." if self.catalog.get("deny_by_default") else "- Deny-by-default posture is not enabled.",
            f"- Live-unknown representation kinds: {', '.join(self.catalog.get('live_unknown_representation', {}).get('unknown_kinds', []))}",
            "",
            "### Dynamic role-discovery rules",
            "",
            render_json_block(
                {
                    "mode": rd.get("mode"),
                    "discovery_primitive_ref": rd.get("discovery_primitive_ref"),
                    "evaluate_every_discovered_role": rd.get("evaluate_every_discovered_role"),
                    "required_roles": rd.get("required_roles"),
                    "prohibited_roles": rd.get("prohibited_roles"),
                    "special_semantic_roles": rd.get("special_semantic_roles"),
                }
            ),
            "",
            "### Relevant-role criteria",
            "",
            "- Evaluate every discovered role.",
            "- Required roles must be present.",
            "- Special semantic roles include PUBLIC and postgres as declared.",
            "",
            "### Governed object kinds",
            "",
        ]
        kinds = sorted({o.get("object_kind") for o in self.catalog["objects"]})
        for k in kinds:
            lines.append(f"- {k}")
        lines += ["", "### Query primitive inventory", ""]
        for p in sorted(self.primitives):
            lines.append(f"- {p}")
        lines += [
            "",
            "### Natural-identity rules",
            "",
            "- Natural identity uses declared identity field paths only.",
            "- OID, object_oid, relation_oid, function_oid, row_number, physical_location, and ctid are prohibited as identity fields.",
            "",
            "### Unstable-field prohibitions",
            "",
            "- Unstable physical identifiers and OID-derived fields are prohibited in natural identity and digest identity contracts.",
            "",
            "## 9.4 Privilege architecture",
            "",
            "### Privilege paths",
            "",
        ]
        for p in self.catalog.get("privilege_paths") or []:
            lines.append(f"- {PRIV_PATH_DISPLAY.get(p, p)}")
        lines += [
            "",
            "### Schemas",
            "",
            "- Schema privileges are evaluated through schema privilege and ownership inventory primitives.",
            f"- Dimensions: {', '.join(self.catalog.get('privilege_dimensions') or [])}",
            "",
            "### Functions",
            "",
            "Function ACL:",
            "",
            "```text",
            "COALESCE(proacl, acldefault('f', proowner))",
            "```",
            "",
            render_json_block(self.catalog.get("function_acl_semantics") or {}),
            "",
            "### Tables",
            "",
            "Table ACL:",
            "",
            "```text",
            "COALESCE(relacl, acldefault('r', relowner))",
            "```",
            "",
            render_json_block(self.catalog.get("table_acl_semantics") or {}),
            "",
            "### Sequences",
            "",
            "Sequence ACL:",
            "",
            "```text",
            "COALESCE(relacl, acldefault('s', relowner))",
            "```",
            "",
            render_json_block(self.catalog.get("sequence_acl_semantics") or {}),
            "",
            "### Columns",
            "",
            "Column ACL:",
            "",
            "```text",
            "NULL attacl means no column-specific ACL.",
            "acldefault('c', ...) is prohibited.",
            "```",
            "",
            render_json_block(self.catalog.get("column_acl_semantics") or {}),
            "",
            "### Default privileges",
            "",
            f"- Default privilege records present: {len(self.catalog.get('default_privileges') or [])}",
            "- Owner-derived default privilege provenance is part of the privilege model.",
            "",
            "## 9.5 Checkpoint registry",
            "",
        ]
        # Render in stable checkpoint_id order already sorted; also show ckp_ref
        for c in sorted(self.checkpoints, key=lambda x: (x.get("ckp_ref") or "", x["checkpoint_id"])):
            lines += [
                f"### {c.get('ckp_ref', c['checkpoint_id'])}: {c['checkpoint_id']}",
                "",
                f"- Checkpoint ID: `{c['checkpoint_id']}`",
                f"- Name: {c.get('name', '')}",
                f"- ND provenance: {', '.join(sorted(c.get('decision_refs') or []))}",
                f"- Evidence marker: {c.get('evidence_marker', {}).get('marker_id', '')}",
                f"- Evidence refs: {', '.join(sorted(c.get('evidence_marker', {}).get('evidence_refs') or []))}",
                f"- Evidence class: {c.get('evidence_class', '')}",
                f"- Failure state: {c.get('failure_state', '')}",
                "",
                "Object selector:",
                "",
                render_json_block(c.get("object_selector") or {}),
                "",
                "Parameters:",
                "",
                render_json_block((c.get("object_selector") or {}).get("parameters") or {}),
                "",
                "Natural identity:",
                "",
                render_json_block(c.get("identity_fields") or {}),
                "",
                "Selected fields:",
                "",
                render_json_block(c.get("selected_fields") or []),
                "",
                "Ordering:",
                "",
                render_json_block(c.get("ordering") or {}),
                "",
                "Serialization:",
                "",
                render_json_block(c.get("serialization") or {}),
                "",
                "Digest:",
                "",
                render_json_block(c.get("digest") or {}),
                "",
                "Empty-set / baseline predicate:",
                "",
                render_predicate(c.get("baseline_predicate") or {}),
                "",
                "Completion predicate:",
                "",
                render_predicate(c.get("completion_predicate") or {}),
                "",
                "No-op predicate:",
                "",
                render_predicate(c.get("noop_predicate") or {}),
                "",
                "Conflict predicate:",
                "",
                render_predicate(c.get("conflict_predicate") or {}),
                "",
                "Bidirectional validation:",
                "",
                render_json_block(c.get("bidirectional_validation") or {}),
                "",
            ]

        # 9.6 Rules
        lines += ["## 9.6 Reconciliation cascade", ""]
        for r in self.rules:
            lines += [
                f"### Order {r['order']}: {r['rule_id']} — {r.get('name', '')}",
                "",
                f"- Order: {r['order']}",
                f"- ID: `{r['rule_id']}`",
                f"- Name: {r.get('name', '')}",
                f"- Fallback: {'yes' if r.get('is_fallback') else 'no'}",
                f"- Evidence class: {r.get('evidence_class', '')}",
                f"- Failure state: {r.get('failure_state', '')}",
            ]
            if r.get("is_fallback"):
                lines += [
                    "- Reachable: yes",
                    "- Concrete fallback condition: missing required status",
                ]
            lines += [
                "",
                "Predicate AST:",
                "",
                render_predicate(r.get("predicate") or {}),
                "",
                "Explicit exclusions:",
                "",
                render_json_block(r.get("explicit_exclusions") or []),
                "",
                "Decisive fields:",
                "",
                render_json_block(r.get("decisive_fields") or []),
                "",
                "Source identity:",
                "",
                render_json_block(r.get("source_identity") or {}),
                "",
                "Outcome slot:",
                "",
                render_json_block(r.get("outcome_slot") or {}),
                "",
                "Capacity effect:",
                "",
                render_json_block(r.get("capacity_effect") or {}),
                "",
                "Event action:",
                "",
                render_json_block(r.get("event_action") or {}),
                "",
                "Archive action:",
                "",
                render_json_block(r.get("archive_action") or {}),
                "",
                "Discrepancy action:",
                "",
                render_json_block(r.get("discrepancy_action") or {}),
                "",
                "Pilot state:",
                "",
                render_json_block(r.get("pilot_state") or {}),
                "",
                "Owner action:",
                "",
                render_json_block(r.get("owner_action") or {}),
                "",
                "Audit artifacts:",
                "",
                render_json_block(r.get("audit_artifacts") or []),
                "",
            ]

        # 9.7
        lines += [
            "## 9.7 Mapping and state proofs",
            "",
            "### Exactly-one outcome-slot contract",
            "",
            "- Each reconciled source must map to exactly one outcome slot under the ordered cascade.",
            "- Zero-slot and multi-slot violations are fail-closed and covered by mapping fixtures.",
            "",
            "### Shared-event source-reference rules",
            "",
            "- Shared-event natural keys and source-domain primitives constrain event linkage.",
            "- Mapping fixtures enumerate allowed and fail-closed shared-event cases.",
            "",
            "### State A identity sets",
            "",
            f"- State A fixture count: {len(self._state_a)}",
        ]
        for fx in self._state_a:
            lines.append(f"- `{fx['fixture_id']}` → expected state `{sanitize_text(fx.get('expected_state'))}`")
        lines += [
            "",
            "### State B independent recomputation requirements",
            "",
            f"- State B fixture count: {len(self._state_b)}",
            "- Invalid State B cases must resolve to failed_frozen.",
        ]
        for fx in self._state_b:
            lines.append(f"- `{fx['fixture_id']}` → expected state `{sanitize_text(fx.get('expected_state'))}`")
        lines += [
            "",
            "### Failure behavior",
            "",
            "- Fail closed on mapping, State A, and State B violations.",
            "- Fallback RULE-22 yields failed_frozen when no earlier rule matches and required status is missing.",
            "",
            "## 9.8 Execution gates",
            "",
            "### Live-preflight gates (11)",
            "",
        ]
        for m in self.markers:
            if m["provenance"]["evidence_class"] == "EXECUTION_TIME_LIVE_PREFLIGHT":
                lines.append(f"- `{m['attributes']['marker_id']}`")
        lines += ["", "### Runtime-revalidation gates (3)", ""]
        for m in self.markers:
            if m["provenance"]["evidence_class"] == "PILOT_TIME_RUNTIME_REVALIDATION":
                lines.append(f"- `{m['attributes']['marker_id']}`")
        lines += [
            "",
            "### Allowed comparison outcomes",
            "",
        ]
        for o in outcomes:
            lines.append(f"- {o}")
        lines += [
            "",
            "### Fail-closed behavior",
            "",
            "- Missing required objects, unsafe undeclared variance, privilege expansion, and runtime state mismatch fail closed.",
            "",
            "### Prohibition on automatic privilege repair",
            "",
            "- Automatic privilege repair is prohibited; owner action is required for privilege discrepancies.",
            "",
            "## 9.9 Security invariants",
            "",
            "- No live provider/model calls during offline validation or documentation generation.",
            "- No paid usage.",
            "- No workflow activation.",
            "- No secret extraction.",
            "- No schema-9 execution before preflight.",
            "- No pilot before runtime revalidation.",
            "- No silent extra-object acceptance.",
            "- No SENTINEL modification.",
            "- No Equitify access.",
            "",
        ]
        return "\n".join(lines)

    def render_verification(self) -> str:
        lines: list[str] = [BANNER.rstrip(), "", "# Round 5A Architecture Reset — Generated Verification Specification", ""]
        lines += [
            "## 10.1 Validator overview",
            "",
            "### Validator CLI",
            "",
            "```text",
            "python tools/validate_round5a.py --root . --report <report.json>",
            "```",
            "",
            "### Exit codes",
            "",
            "- 0 = PASS",
            "- 1 = FAIL (specification/semantic failure)",
            "- 2 = BLOCKED / environment failure",
            "",
            "### Validation stages",
            "",
            "- file presence and JSON load",
            "- schema validation",
            "- manifest integrity",
            "- cross-file references",
            "- catalog semantics",
            "- checkpoint semantics",
            "- reconciliation semantics",
            "- fixture coverage",
            "- shadowing / first-match ownership",
            "- mapping invariants",
            "- state invariants",
            "- privilege semantics",
            "- evidence class invariants",
            "- evidence source hash integrity (R5A-PROV-SOURCE-*)",
            "- evidence alias resolution (R5A-PROV-ALIAS-*)",
            "- split/merge field coverage",
            "- portable path invariants (R5A-PROV-PATH-*)",
            "- false historical-authentication detection (R5A-PROV-AUTH-*)",
            "- final summary",
            "",
            "### Deterministic-report fields",
            "",
            "- final_status",
            "- errors (sorted)",
            "- stage results with stable counts",
            "- offline acceptance does not require an emission timestamp field",
            "",
            "### Stable error-code namespaces",
            "",
            "- R5A-FILE-*",
            "- R5A-SCHEMA-*",
            "- R5A-MANIFEST-*",
            "- R5A-REF-*",
            "- R5A-CATALOG-*",
            "- R5A-EVIDENCE-*",
            "- R5A-CKP-*",
            "- R5A-RULE-*",
            "- R5A-FIXTURE-*",
            "- R5A-SHADOW-*",
            "- R5A-MAPPING-*",
            "- R5A-STATE-*",
            "- R5A-PROV-*",
            "- R5A-PRIV-*",
            "",
            "## 10.2 Reconciliation coverage",
            "",
            f"- Positive / fallback witnesses: {len(self._pos)} (W1–W22)",
            f"- Boundary witnesses: {len(self._bounds)} (B1–B21)",
            f"- Shadowing pairs: {self.result.counts['shadowing_pairs']}",
            f"- Mutation fixtures: {len(self._muts)}",
            f"- Reachable rules: 22",
            "- Fallback reachability: RULE-22 reachable → failed_frozen via missing required status",
            "",
            "### Decisive fields",
            "",
            "| Rule | Decisive fields |",
            "| --- | --- |",
        ]
        for r in self.rules:
            fields = ", ".join(".".join(df["path"]) for df in r.get("decisive_fields") or [])
            lines.append(f"| {r['rule_id']} | {md_escape(fields)} |")
        lines += ["", "### Witnesses W1–W22", "", "| Fixture ID | Target rule | Earlier false rules | Expected outcome slot | Expected state |", "| --- | --- | --- | --- | --- |"]
        for fx in sorted(self._pos, key=lambda f: f["fixture_id"]):
            earlier = ", ".join(fx.get("earlier_rules_expected_false") or [])
            slot = sanitize_text(fx.get("expected_outcome_slot"))
            state = sanitize_text(fx.get("expected_state"))
            lines.append(
                f"| {fx['fixture_id']} | {fx.get('expected_rule', '')} | {md_escape(earlier)} | {md_escape(slot)} | {md_escape(state)} |"
            )
        lines += ["", "### Boundaries B1–B21", "", "| Fixture ID | Source witness | Mutation | Original rule | Expected new owner |", "| --- | --- | --- | --- | --- |"]
        for fx in sorted(self._bounds, key=lambda f: f["fixture_id"]):
            mut = sanitize_text(fx.get("mutations") or fx.get("boundary_mutation") or fx.get("input_records"))
            src = fx.get("source_witness") or fx.get("related_records") or ""
            lines.append(
                f"| {fx['fixture_id']} | {md_escape(sanitize_text(src))} | {md_escape(mut)[:120]} | {fx.get('original_rule', '')} | {fx.get('expected_new_rule', fx.get('expected_rule', ''))} |"
            )
        lines += [
            "",
            "### Mutation coverage",
            "",
            f"- Mutation fixture count: {len(self._muts)}",
            "",
            "| Fixture ID | Original rule | Expected rule | Mutations |",
            "| --- | --- | --- | --- |",
        ]
        for fx in self._muts:
            lines.append(
                f"| {fx['fixture_id']} | {fx.get('original_rule', '')} | {fx.get('expected_rule', '')} | {md_escape(sanitize_text(fx.get('mutations')))[:120]} |"
            )

        # 10.3
        lines += ["", "## 10.3 Mapping and state coverage", "", "### Mapping fixtures", ""]
        lines += ["| Fixture ID | Expected rule | Expected state | Classification |", "| --- | --- | --- | --- |"]
        for fx in self._maps:
            state_val = ""
            es = fx.get("expected_state")
            if isinstance(es, dict):
                state_val = str(es.get("value", es))
            else:
                state_val = str(es)
            classification = "expected PASS"
            if "fail" in state_val.lower() or state_val == "failed_frozen":
                classification = "expected fail-closed / failed_frozen"
            elif "invalid" in state_val.lower() or "zero_slots" in state_val.lower():
                classification = "expected fail-closed"
            lines.append(f"| {fx['fixture_id']} | {fx.get('expected_rule', '')} | {md_escape(state_val)} | {classification} |")
        lines += ["", "### State A fixtures", "", "| Fixture ID | Expected state |", "| --- | --- |"]
        for fx in self._state_a:
            lines.append(f"| {fx['fixture_id']} | {md_escape(sanitize_text(fx.get('expected_state')))} |")
        lines += ["", "### State B fixtures", "", "| Fixture ID | Expected state |", "| --- | --- |"]
        for fx in self._state_b:
            lines.append(f"| {fx['fixture_id']} | {md_escape(sanitize_text(fx.get('expected_state')))} |")

        # 10.4
        lines += [
            "",
            "## 10.4 Checkpoint oracle coverage",
            "",
            f"- Checkpoint count: {len(self.checkpoints)}",
            f"- Oracle count: {len(self.oracles)}",
            "",
            "| Checkpoint | Oracle IDs | Algorithm version | Expected digest | Expected result | Case kind |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
        by_cp: dict[str, list[dict[str, Any]]] = {}
        for o in self.oracles:
            by_cp.setdefault(o["checkpoint_ref"], []).append(o)
        for c in sorted(self.checkpoints, key=lambda x: x["checkpoint_id"]):
            ors = by_cp.get(c["checkpoint_id"], [])
            if not ors:
                lines.append(f"| {c['checkpoint_id']} |  |  |  |  |  |")
            for o in sorted(ors, key=lambda x: x["oracle_id"]):
                lines.append(
                    f"| {c['checkpoint_id']} | {o['oracle_id']} | {o.get('algorithm_version', '')} | `{o.get('expected_digest', '')}` | {o.get('expected_result', '')} | {o.get('case_kind', '')} |"
                )
        lines += ["", "### Canonicalization edge cases", ""]
        for o in self.oracles:
            if o.get("case_kind") and o["case_kind"] != "happy_path":
                lines.append(f"- `{o['oracle_id']}` case_kind={o['case_kind']} expected_result={o.get('expected_result')}")

        # 10.5
        lines += ["", "## 10.5 Privilege fixture coverage", ""]
        for kind in ["SCHEMA", "FUNCTION", "TABLE", "COLUMN", "SEQUENCE"]:
            rows = [f for f in self.privileges if f["object_kind"] == kind]
            lines += [f"### {kind}", "", f"- Fixture count: {len(rows)}", "", "| Fixture ID | Expected paths | Exercisable privileges | Default ACL semantics |", "| --- | --- | --- | --- |"]
            for f in rows:
                lines.append(
                    f"| {f['fixture_id']} | {md_escape(sanitize_text(f.get('expected_paths')))} | {md_escape(sanitize_text(f.get('expected_exercisable_privileges')))} | {md_escape(sanitize_text(f.get('default_acl_semantics')))} |"
                )
            lines.append("")
        lines += [
            "### Default-privilege provenance",
            "",
            "- Privilege fixtures include default ACL semantics and owner-derived provenance expectations.",
            "",
            "## 10.6 Evidence coverage",
            "",
            "| Marker | Class | Positive obligation | Missing obligation | Mismatch obligation | Fail-closed obligation |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
        for m in self.markers:
            a = m["attributes"]
            cls = m["provenance"]["evidence_class"]
            outcomes = str(a.get("comparison_outcomes", ""))
            lines.append(
                "| "
                + " | ".join(
                    md_escape(x)
                    for x in [
                        a["marker_id"],
                        cls,
                        "MATCHES_RECONSTRUCTED_REFERENCE" if "MATCHES_RECONSTRUCTED_REFERENCE" in outcomes else required_gate(cls),
                        "MISSING_REQUIRED_OBJECT" if "MISSING_REQUIRED_OBJECT" in outcomes else "as declared",
                        "UNSAFE_UNDECLARED_VARIANCE / OWNER_MISMATCH / RUNTIME_STATE_MISMATCH as declared",
                        a.get("failure_behavior", "failed_frozen"),
                    ]
                )
                + " |"
            )

        # 10.7
        test_path = self.root / "tests" / "test_validate_round5a.py"
        inventory = extract_test_inventory(test_path) if test_path.exists() else []
        lines += [
            "",
            "## 10.7 Focused validator-test inventory",
            "",
            f"- Test functions present: {len(inventory)}",
            "- Success metric is focused-test pass/fail. The legacy 777 metric is not used.",
            "",
            "| Test function | Validated error codes |",
            "| --- | --- |",
        ]
        for name, codes in inventory:
            lines.append(f"| {name} | {', '.join(codes) if codes else '(pass-path / no code asserted)'} |")

        lines += [
            "",
            "## 10.8 Acceptance commands",
            "",
            "```powershell",
            "python tools/validate_round5a.py --root . --report <report.json>",
            "python -m pytest tests/test_validate_round5a.py -q",
            "python tools/generate_round5a_docs.py --root . --check",
            "python -m pytest tests/test_generate_round5a_docs.py -q",
            "```",
            "",
            "Database integration, schema-9 execution, live preflight, and runtime revalidation are not performed by these commands.",
            "",
        ]
        return "\n".join(lines)

    def render_traceability(self) -> str:
        lines: list[str] = [BANNER.rstrip(), "", "# Round 5A Architecture Reset — Generated Traceability", ""]
        # Build indexes
        nd_to: dict[str, dict[str, set[str]]] = {nd: {"registry": set(), "checkpoints": set(), "rules": set(), "markers": set(), "fixtures": set(), "sections": set()} for nd in sorted(self.nd_refs)}
        for m in self.markers:
            for nd in m["provenance"].get("decision_refs") or []:
                if nd in nd_to:
                    nd_to[nd]["markers"].add(m["attributes"]["marker_id"])
                    nd_to[nd]["registry"].add("catalog_contract.yaml")
                    nd_to[nd]["sections"].add("ARCHITECTURE.md#92-evidence-model")
        for c in self.checkpoints:
            for nd in c.get("decision_refs") or []:
                if nd in nd_to:
                    nd_to[nd]["checkpoints"].add(c["checkpoint_id"])
                    nd_to[nd]["registry"].add("checkpoints.yaml")
                    nd_to[nd]["sections"].add("ARCHITECTURE.md#95-checkpoint-registry")
        for r in self.rules:
            for nd in r.get("decision_refs") or []:
                if nd in nd_to:
                    nd_to[nd]["rules"].add(r["rule_id"])
                    nd_to[nd]["registry"].add("reconciliation_rules.yaml")
                    nd_to[nd]["sections"].add("ARCHITECTURE.md#96-reconciliation-cascade")
        for fx in self.fixtures:
            # fixtures may not have decision_refs; link via expected_rule/checkpoint later
            pass
        # also scan provenance blocks
        for rel, key in [
            ("specs/round5a/catalog_contract.yaml", "catalog"),
            ("specs/round5a/checkpoints.yaml", "checkpoints"),
            ("specs/round5a/reconciliation_rules.yaml", "rules"),
            ("specs/round5a/fixtures/reconciliation_witnesses.yaml", "fixtures"),
            ("specs/round5a/fixtures/checkpoint_oracles.yaml", "oracles"),
            ("specs/round5a/fixtures/privilege_cases.yaml", "privileges"),
        ]:
            doc = self.docs[rel]
            prov = doc.get("provenance") or {}
            for nd in prov.get("decision_refs") or []:
                if nd in nd_to:
                    nd_to[nd]["registry"].add(Path(rel).name)
                    nd_to[nd]["sections"].add("TRACEABILITY.md#decisions")

        lines += [
            "## Decisions",
            "",
            "| ND ID | Registry records | Checkpoints | Rules | Markers | Fixtures | Generated sections |",
            "| --- | --- | --- | --- | --- | --- | --- |",
        ]
        # attach fixtures mentioning ND in JSON text
        fixture_text_index: dict[str, set[str]] = {nd: set() for nd in self.nd_refs}
        for fx in self.fixtures:
            raw = json.dumps(fx, sort_keys=True)
            for nd in self.nd_refs:
                if nd in raw:
                    fixture_text_index[nd].add(fx["fixture_id"])
        for nd in sorted(nd_to):
            row = nd_to[nd]
            fixtures = sorted(fixture_text_index.get(nd) or [])
            lines.append(
                "| "
                + " | ".join(
                    [
                        nd,
                        md_escape(", ".join(sorted(row["registry"])) or "—"),
                        md_escape(", ".join(sorted(row["checkpoints"])) or "—"),
                        md_escape(", ".join(sorted(row["rules"])) or "—"),
                        md_escape(", ".join(sorted(row["markers"])) or "—"),
                        md_escape(", ".join(fixtures) or "—"),
                        md_escape(", ".join(sorted(row["sections"])) or "ARCHITECTURE.md"),
                    ]
                )
                + " |"
            )

        # Evidence
        lines += [
            "",
            "## Evidence",
            "",
            "| EV or marker | Evidence class | Registry records | Checkpoints | Rules | Fixtures | Required runtime gate |",
            "| --- | --- | --- | --- | --- | --- | --- |",
        ]
        marker_by_ev = {}
        for m in self.markers:
            for ev in m["provenance"].get("evidence_refs") or []:
                marker_by_ev[ev] = m
            marker_by_ev[m["attributes"]["marker_id"]] = m
        for key in sorted(set(self.ev_refs) | {m["attributes"]["marker_id"] for m in self.markers}):
            m = marker_by_ev.get(key)
            if m is None:
                # EV mentioned but maybe only in provenance
                cls = "—"
                gate = "—"
                reg = "registry provenance"
                cps = "—"
                rules = "—"
                fxs = "—"
            else:
                cls = m["provenance"]["evidence_class"]
                gate = required_gate(cls)
                reg = "catalog_contract.yaml"
                cps = ", ".join(
                    sorted(
                        c["checkpoint_id"]
                        for c in self.checkpoints
                        if c.get("evidence_marker", {}).get("marker_id") == m["attributes"]["marker_id"]
                        or key in (c.get("evidence_marker", {}).get("evidence_refs") or [])
                    )
                ) or "—"
                rules = ", ".join(
                    sorted(r["rule_id"] for r in self.rules if key in (r.get("decision_refs") or []) or key in json.dumps(r.get("audit_artifacts") or []))
                ) or "—"
                # also rules with matching evidence class refs in provenance of rules file
                rules2 = [
                    r["rule_id"]
                    for r in self.rules
                    if key in json.dumps({"e": r.get("evidence_class"), "d": r.get("decision_refs")})
                ]
                if not rules or rules == "—":
                    # link via evidence_class only if EV appears in rule provenance top-level — skip
                    rules = "—"
                fxs = ", ".join(
                    sorted(
                        f["fixture_id"]
                        for f in self.fixtures
                        if key in json.dumps(f)
                    )[:12]
                ) or "—"
            lines.append(
                f"| {key} | {cls if m else '—'} | {reg if m else '—'} | {md_escape(cps)} | {md_escape(rules)} | {md_escape(fxs)} | {gate if m else '—'} |"
            )

        # Checkpoints
        lines += [
            "",
            "## Checkpoints",
            "",
            "| Checkpoint | Primitive | Evidence marker | Oracle IDs | Validator checks | Architecture section |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
        for c in sorted(self.checkpoints, key=lambda x: x["checkpoint_id"]):
            ors = ", ".join(sorted(o["oracle_id"] for o in self.oracles if o["checkpoint_ref"] == c["checkpoint_id"]))
            lines.append(
                f"| {c['checkpoint_id']} | {c.get('object_selector', {}).get('primitive_ref', '')} | {c.get('evidence_marker', {}).get('marker_id', '')} | {md_escape(ors)} | R5A-CKP-* digest/identity | ARCHITECTURE.md#95-checkpoint-registry |"
            )

        # Rules
        lines += [
            "",
            "## Rules",
            "",
            "| Rule | Witness | Boundary | Mutation fixtures | Outcome slot | Validator checks | Architecture section |",
            "| --- | --- | --- | --- | --- | --- | --- |",
        ]
        for r in self.rules:
            w = ", ".join(f["fixture_id"] for f in self._pos if f.get("expected_rule") == r["rule_id"])
            b = ", ".join(
                f["fixture_id"]
                for f in self._bounds
                if f.get("original_rule") == r["rule_id"] or f.get("expected_new_rule") == r["rule_id"] or f.get("expected_rule") == r["rule_id"]
            )
            mut = ", ".join(f["fixture_id"] for f in self._muts if f.get("original_rule") == r["rule_id"] or f.get("expected_rule") == r["rule_id"])
            slot = sanitize_text(r.get("outcome_slot"))
            lines.append(
                f"| {r['rule_id']} | {md_escape(w) or '—'} | {md_escape(b) or '—'} | {md_escape(mut) or '—'} | {md_escape(slot)[:80]} | R5A-RULE-* / R5A-FIXTURE-* | ARCHITECTURE.md#96-reconciliation-cascade |"
            )

        # Privileges
        lines += [
            "",
            "## Privileges",
            "",
            "| Object kind | Contract records | Fixture IDs | Validator checks | Generated section |",
            "| --- | --- | --- | --- | --- |",
        ]
        for kind in ["SCHEMA", "FUNCTION", "TABLE", "COLUMN", "SEQUENCE"]:
            fxs = ", ".join(f["fixture_id"] for f in self.privileges if f["object_kind"] == kind)
            contract = {
                "SCHEMA": "schema privileges / role discovery",
                "FUNCTION": "function_acl_semantics",
                "TABLE": "table_acl_semantics",
                "COLUMN": "column_acl_semantics",
                "SEQUENCE": "sequence_acl_semantics",
            }[kind]
            lines.append(
                f"| {kind} | {contract} | {md_escape(fxs)} | R5A-PRIV-* | ARCHITECTURE.md#94-privilege-architecture / VERIFICATION.md#105-privilege-fixture-coverage |"
            )

        lines.extend([
            "",
            "## Evidence aliases",
            "",
            "| Archived EV | Mapping type | Recreated EV | Current EV | Affected markers | Decision | Status |",
            "|---|---|---|---|---|---|---|",
        ])
        mappings = sorted(
            (self.aliases.get("evidence_alias_registry") or {}).get("mappings") or [],
            key=lambda m: m.get("mapping_id", ""),
        )
        blocking = [
            m
            for m in mappings
            if m.get("status") == "BLOCKING_CONFLICT" or m.get("mapping_type") == "CONFLICTING_MEANING"
        ]
        if blocking:
            self.result.fail(
                GenError(
                    "R5A-GEN-TRACE-ALIAS-CONFLICT",
                    "blocking conflict mapping cannot appear in PASS documentation",
                    "evidence_aliases.yaml",
                    blocking[0].get("mapping_id", ""),
                )
            )
        covered_markers: set[str] = set()
        for m in mappings:
            archived = ", ".join(m.get("archived_evidence_ids") or []) or "—"
            recreated = ", ".join(m.get("recreated_evidence_ids") or []) or "—"
            current = ", ".join(m.get("current_evidence_ids") or []) or "—"
            markers = ", ".join(m.get("affected_markers") or []) or "—"
            covered_markers.update(m.get("affected_markers") or [])
            decisions = ", ".join(m.get("decision_refs") or [])
            lines.append(
                f"| {md_escape(archived)} | {m.get('mapping_type', '')} | {md_escape(recreated)} | "
                f"{md_escape(current)} | {md_escape(markers)} | {md_escape(decisions)} | {m.get('status', '')} |"
            )
        lines.extend(["", f"Alias mappings rendered: {len(mappings)}", ""])
        for mobj in self.markers:
            mk = mobj["attributes"]["marker_id"]
            cls = mobj["provenance"]["evidence_class"]
            if mk not in covered_markers:
                if cls in {"EXECUTION_TIME_LIVE_PREFLIGHT", "PILOT_TIME_RUNTIME_REVALIDATION"}:
                    lines.append(f"- {mk} resolves via live/runtime unknown gate ({cls})")
                else:
                    self.result.fail(
                        GenError(
                            "R5A-GEN-TRACE-ALIAS-UNRESOLVED",
                            f"marker {mk} not resolved by alias table or live/runtime gate",
                            "TRACEABILITY.md",
                            mk,
                        )
                    )
        lines.append("")
        lines.append("Historical authentication rendered: `UNVERIFIED`")
        lines.append("")

        lines += [
            "",
            "## Coverage guarantees",
            "",
            f"- ND references listed: {len(self.nd_refs)}",
            f"- Evidence markers listed: {len(self.markers)}",
            f"- Checkpoints listed: {len(self.checkpoints)}",
            f"- Rules listed: {len(self.rules)}",
            f"- Reconciliation fixtures referenced: {len(self.fixtures)}",
            f"- Privilege fixtures referenced: {len(self.privileges)}",
            f"- Checkpoint oracles referenced: {len(self.oracles)}",
            "- No dangling generated references are permitted by pre-render integrity.",
            "- Normative registry records are documented through the tables above.",
            "",
        ]
        return "\n".join(lines)

    def render_manifest(self, output_hashes: dict[str, str]) -> dict[str, Any]:
        normative = {rel: self.source_hashes[rel] for rel in NORMATIVE_HASH_PATHS}
        return {
            "generator_name": GENERATOR_NAME,
            "generator_version": GENERATOR_VERSION,
            "specification_schema_version": self.schema_version,
            "registry_version": self.registry_version,
            "normative_sources": {k: normative[k] for k in sorted(normative)},
            "generated_outputs": {
                k: output_hashes[k]
                for k in [
                    "docs/generated/round5a/ARCHITECTURE.md",
                    "docs/generated/round5a/VERIFICATION.md",
                    "docs/generated/round5a/TRACEABILITY.md",
                ]
            },
            "counts": {
                "evidence_markers": 31,
                "reconstructed": 17,
                "live_preflight": 11,
                "runtime_revalidation": 3,
                "checkpoints": 18,
                "rules": 22,
                "witnesses": 22,
                "boundaries": 21,
                "shadowing_pairs": 231,
            },
        }

    def render_all(self) -> dict[str, bytes]:
        arch = utf8_lf(self.render_architecture())
        ver = utf8_lf(self.render_verification())
        trace = utf8_lf(self.render_traceability())
        hashes = {
            "docs/generated/round5a/ARCHITECTURE.md": sha256_bytes(arch),
            "docs/generated/round5a/VERIFICATION.md": sha256_bytes(ver),
            "docs/generated/round5a/TRACEABILITY.md": sha256_bytes(trace),
        }
        manifest = json_dump(self.render_manifest(hashes))
        # Ensure generated content has no forbidden patterns
        for rel, data in [
            ("ARCHITECTURE.md", arch),
            ("VERIFICATION.md", ver),
            ("TRACEABILITY.md", trace),
            ("generation_manifest.json", manifest),
        ]:
            text = data.decode("utf-8")
            if "generated_at" in text:
                self.result.fail(GenError("R5A-GEN-OUTPUT-TIMESTAMP", f"generated_at forbidden in {rel}", rel))
            if ABS_PATH_RE.search(text.replace("/", "\\")) or "AppData/Local/Temp" in text.replace("\\", "/"):
                # Allow only if somehow; fail on TEMP
                if re.search(r"(?i)AppData/Local/Temp|/Users/|C:/Users/", text.replace("\\", "/")):
                    self.result.fail(GenError("R5A-GEN-OUTPUT-PATH", f"absolute/TEMP path leaked in {rel}", rel))
        return {
            "docs/generated/round5a/ARCHITECTURE.md": arch,
            "docs/generated/round5a/VERIFICATION.md": ver,
            "docs/generated/round5a/TRACEABILITY.md": trace,
            "docs/generated/round5a/generation_manifest.json": manifest,
        }

    def first_diff_line(self, expected: bytes, actual: bytes) -> str:
        exp_lines = expected.decode("utf-8", errors="replace").splitlines()
        act_lines = actual.decode("utf-8", errors="replace").splitlines()
        limit = max(len(exp_lines), len(act_lines))
        for i in range(limit):
            e = exp_lines[i] if i < len(exp_lines) else "<missing>"
            a = act_lines[i] if i < len(act_lines) else "<missing>"
            if e != a:
                return f"line {i + 1}: expected={e!r} actual={a!r}"
        return "bytes differ without line boundary difference"

    def write_outputs(self, rendered: dict[str, bytes]) -> None:
        for rel, data in rendered.items():
            path = confine(self.root, rel)
            path.parent.mkdir(parents=True, exist_ok=True)
            if path.exists():
                current = path.read_bytes()
                if current == data:
                    self.result.unchanged.append(rel)
                    continue
                action = "updated"
            else:
                action = "created"
            fd, tmp_name = tempfile.mkstemp(prefix="r5a-gen-", suffix=".tmp", dir=str(path.parent))
            os.close(fd)
            tmp_path = Path(tmp_name)
            try:
                tmp_path.write_bytes(data)
                tmp_path.replace(path)
            finally:
                if tmp_path.exists():
                    try:
                        tmp_path.unlink()
                    except OSError:
                        pass
            if action == "created":
                self.result.created.append(rel)
            else:
                self.result.updated.append(rel)
            self.result.outputs[rel] = sha256_bytes(data)

    def check_outputs(self, rendered: dict[str, bytes]) -> None:
        for rel, data in rendered.items():
            path = confine(self.root, rel)
            if not path.exists():
                self.result.fail(GenError("R5A-GEN-DRIFT-MISSING", f"missing generated output {rel}", rel))
                self.result.drift.append({"file": rel, "detail": "missing"})
                continue
            actual = path.read_bytes()
            if actual != data:
                detail = self.first_diff_line(data, actual)
                self.result.fail(GenError("R5A-GEN-DRIFT-MISMATCH", f"drift in {rel}: {detail}", rel))
                self.result.drift.append({"file": rel, "detail": detail})
            else:
                self.result.unchanged.append(rel)
                self.result.outputs[rel] = sha256_bytes(data)
        # extra files in generated dir?
        gen_dir = confine(self.root, "docs/generated/round5a")
        if gen_dir.exists():
            expected = set(OUTPUT_REL_PATHS)
            for p in sorted(gen_dir.iterdir()):
                if p.is_file():
                    rel = f"docs/generated/round5a/{p.name}"
                    if rel not in expected:
                        self.result.fail(GenError("R5A-GEN-DRIFT-EXTRA", f"extra generated file {rel}", rel))
                        self.result.drift.append({"file": rel, "detail": "extra"})


def generate(root: Path, mode: str) -> GenResult:
    gen = Round5ADocGenerator(root)
    gen.load_sources()
    if gen.result.status != "PASS":
        return gen.result
    try:
        code, report = run_phase_d_validator(root)
    except Exception as exc:  # noqa: BLE001
        gen.result.fail(GenError("R5A-GEN-SOURCE-VALIDATOR", f"validator invocation failed: {exc}"))
        gen.result.status = "FAIL"
        return gen.result
    gen.integrity(report, code)
    if gen.result.status != "PASS":
        return gen.result
    rendered = gen.render_all()
    if gen.result.status != "PASS":
        return gen.result
    if mode == "write":
        gen.write_outputs(rendered)
    else:
        gen.check_outputs(rendered)
    if gen.result.errors:
        gen.result.status = "FAIL"
    else:
        gen.result.status = "PASS"
    # fill output hashes for report
    for rel, data in rendered.items():
        gen.result.outputs[rel] = sha256_bytes(data)
    return gen.result


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate Round 5A non-normative documentation")
    parser.add_argument("--root", required=True, help="repository root")
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="write generated outputs")
    mode.add_argument("--check", action="store_true", help="check generated outputs for drift")
    parser.add_argument("--report", help="optional JSON report path")
    args = parser.parse_args(argv)

    root = Path(args.root)
    if not root.exists():
        print("root does not exist", file=sys.stderr)
        return 2
    try:
        result = generate(root.resolve(), "write" if args.write else "check")
    except FileNotFoundError as exc:
        print(f"file failure: {exc}", file=sys.stderr)
        return 2
    except ValueError as exc:
        print(f"environment failure: {exc}", file=sys.stderr)
        return 2
    except Exception as exc:  # noqa: BLE001
        print(f"generator failure: {exc}", file=sys.stderr)
        return 2

    report = result.as_dict()
    if args.report:
        report_path = Path(args.report)
        report_path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    print(f"status={result.status} drift={len(result.drift)} errors={len(result.errors)}")
    if result.status == "PASS":
        return 0
    # 2 = usage/dependency/file/environment; 1 = drift or specification failure
    if any(
        e.code.startswith("R5A-GEN-FILE-")
        or e.code
        in {
            "R5A-GEN-SOURCE-JSON",
            "R5A-GEN-MANIFEST-MISSING",
            "R5A-GEN-MANIFEST-ESCAPE",
        }
        for e in result.errors
    ):
        return 2
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
